### ISSUE TITLE
No audio in calls

### ISSUE THREAD

**Issue by dirkz** [WhisperSystems/Signal-iOS#1022]
Most of the time there is no audio when receiving or making calls (maybe that is discernible from the log). The caller and the receiver (there should only be 2 accounts involved in the logs) are in the same WLAN. I have also moved one to a mobile network at least once (with the same result) to make sure that's not the cause of the issue.

Everything seems fine, you receive a call, you accept it, but audio is lacking. This happens in more than half of the cases.

Edit 1: When there is no audio, it's missing on both ends. There was never audio missing on  only one side.

Edit 2: There are some calls without audio starting at 2015/12/21 20:23:16:051.

**Comment by Dutch80210** [comment]
I have the same problem

**Comment by dti-jmflorent** [comment]
An issue with audio failing can be consistently produced.  Assume both instances are freshly restarted (can be done by ending the service rather than restarting the phone).
1 - Initiate call
2 - Set the call to speaker phone
3 - Either party hangs up
4 - Initiate or accept a call from the phone that was previously in speaker : audio is no absent

Restarting Signal will allow normal calling (double tap home, swipe up to close, relaunch app)

**Comment by TreatyOfRome** [comment]
Could be closed due to implementation of WebRTC calling?

**Comment by michaelkirk** [comment]
Thanks @TreatyOfRome

Closing since we've replaced our calling system. If you continue to have the issue, please reopen, including a debug log (from both parties if possible) right after the incident occurs.
