### ISSUE TITLE
bug: messages are not sent but it is displayed in the message thread

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/Signal-iOS#1035]
The last few days it happened a few times that I sent a message which actually wasn't sent and got stuck on sending. I sent another message after the first one and this one got delivered then, but the first one was still stuck and it is until now.

On the screenshot you can see what I tried to describe...

![picture](https://cloud.githubusercontent.com/assets/3447340/12071831/0dc60eec-b0c1-11e5-9088-7edfa286e27b.jpg)

**Comment by Quiark** [comment]
Same here.

**Comment by dphiffer** [comment]
I came here to post this same issue.

**Comment by riyapenn** [comment]
Please refrain from "Same here" "Same issue" "me too" "+1" without providing any NEW or additional information like a [debug log](https://support.whispersystems.org/hc/en-us/articles/229676507-How-do-I-submit-an-iOS-debug-log-or-crash-report-) or actionable items. Otherwise you are creating noise and not contributing to finding a solution. If you _really_ want, there's the emoji option to the top right of the comment header to "add your reaction"

**Comment by riyapenn** [comment]
Debug log of same issue: https://gist.github.com/ad956e2357d071f30bb0538e87e7a4a2

**Comment by riyapenn** [comment]
This can be recreated by swiping the app closed **immediately** after sending a message and [only seeing the message bubble as light blue](https://support.whispersystems.org/hc/en-us/articles/212742268-How-do-I-know-my-message-was-delivered-)
Log: https://gist.github.com/22aab4276d224ab10d74a6e8f70a4e44

Perhaps the other users experiencing this have the same action?

**Comment by charlesmchen** [comment]
We've fixed what we think is the issue here - "unsent" messages not getting labelled as such after an app restart. If this issue recurs, we'll reopen or make a new issue.
