### ISSUE TITLE
Photo attachment corrupted

### ISSUE THREAD

**Issue by SpiraMira** [WhisperSystems/Signal-iOS#1037]
I get blank bubbles with a spinning activity indicator after attempting to attach a photo from the camera ( not from the library). This is a "single user" conversation if that has any bearing on the matter. Tried resetting the session (with long presses) to no avail.

**Comment by michaelkirk** [comment]
Verified this bug in appstore (2.2) and latest master.

- Go to contact thread
- Tap paperclip to open attachment dialog
- Tap "Take Photo or Video"
- Take a photo once Native camera picker opens
- select "use photo"
- Then you'll see a loading indicator for your message which never completes
- And when you tap the message the app crashes with [error]

![image](https://cloud.githubusercontent.com/assets/217057/13716972/4811ba34-e793-11e5-816a-ce71a023f7eb.png)
This is what the loading-indicator looks like.

Worse yet, the recipient sees the same thing in their screen. 

- As the message recipient
- I see a new "loading indicator" message appear in our thread
- When I tap it the app crashes

Interestingly there is *no* problem with captured video. Attaching photo or video from library works fine.

- Go to contact thread
- Tap paperclip to open attachment dialog
- Tap "Take Photo or Video"
- Once Native camera picker opens, slide over to video mode
- Video successfully sends

[error] pulled from Xcode

```
2016-03-11 14:03:18.906 Signal Dev[713:162544] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 323.5]'
```

**Comment by michaelkirk** [comment]
@SpiraMira can you confirm - what version of the app are you using?

I'm seeing a problem with this that seems related to #886, but that code isn't in the appstore yet. So there might be something else causing this problem. My WIP is here: https://github.com/WhisperSystems/Signal-iOS/compare/master...michaelkirk:fix-take-photo-crash%231037?expand=1 which essentially reverts to the existing behavior unless you're uploading an image. 

I suspect this is because [ALAAssetLibrary](https://developer.apple.com/library/ios/documentation/AssetsLibrary/Reference/ALAssetsLibrary_Class/) is only for managing existing assets from your photo roll, not for newly snapped photos returned in a photo picker.
