### ISSUE TITLE
Signal Call Disconnects when I receive a Call on 4S

### ISSUE THREAD

**Issue by Elle-See** [WhisperSystems/Signal-iOS#1039]
Each time I am on a call on Signal and receive a call through my phone, the Signal call disconnects.

The app doesn't crash, just disconnects.

Fixing this would be great!

**Comment by 2-4601** [comment]
What is the expected behaviour? To put the Signal call on hold? #401 related.

**Comment by arekm** [comment]
Any reason why this got closed? Is this not possible with current state of iOS APIs?

Right now this looks like this:
- I'm talking via signal (video)
- someone calls me via phone
- I see notification (just like when having regular phone conversation and second call comes in) and I'm presented with a button to switch to the other - phone - call
- when I do that signal disconnects instead of waiting in background

**Comment by michaelkirk** [comment]
@arekm - what version of iOS are you running?

**Comment by arekm** [comment]
iOS 11.2.5

integration with iOS calling turned on in signal

**Comment by michaelkirk** [comment]
This particular issue is super old and predates our integration with iOS calling. 

Can you open a new issue and include a screenshot of the incoming call screen that you see?

**Comment by arekm** [comment]
Done. https://github.com/signalapp/Signal-iOS/issues/3019
