### ISSUE TITLE
App crashes when attempting to verify.

### ISSUE THREAD

**Issue by Ruukasu** [WhisperSystems/Signal-iOS#1046]
Every time I try to verify, tapping "Verify This Device" crashes this app. I don't know if this is an app issue or an iOS 9.2 issue.

**Comment by riyapenn** [comment]
Same as https://github.com/WhisperSystems/Signal-iOS/issues/979

Check your iPhone's Settings for Signal and enable Background App Refresh + Notifications.  
If you do not see the permissions, then re-install Signal, open Signal, and when you get a pop-up alert "Signal" Would like to Send You Notifications, hit OK. 

Also click on the verification link in the SMS instead of inputting the verification number yourself. 

http://support.whispersystems.org/hc/en-us/articles/213132457-Are-you-having-trouble-verifying-on-Signal-

**Comment by Ruukasu** [comment]
Background App Refresh and Notifications are already enabled. I don't want to have to lose my sessions before my iPhone crashed and restarted, causing my phone number to lose verification. I tried the verification link in the SMS, but it still requires my phone number. Attempting to verify the number causes it to instantly crash.

**Comment by riyapenn** [comment]
contact support@whispersystems.org

**Comment by jpsachse** [comment]
Having had this issue twice and lost all my conversations in both cases since I could only use signal after reinstalling it. The app decided at a certain point that it needed to verify my phone number again and as soon as I did enter it and tapped on the corresponding button, signal crashed without letting me getting to my conversations.

**Comment by michaelkirk** [comment]
@Ruukasu if this is still an issue can you reopen and submit a crash log to support@whispersystems.org?


## To submit your crash report

1. On your phone, open the Settings App
2. Go to Privacy, then Diagnostics & Usage
3. Select Diagnostics & Usage Data
4. Locate the log for the crashed app. Crash logs will be named in the format: Signal-(DateTime).ips
5. Select the desired log. Then, using the text selection UI select the entire text of the log. Once the text is selected, tap Copy
6. Paste the copied text into an email to support@whispersystems.org with the subject "iOS Crash Log: &lt;Github Issue Reference&gt;"
  * **Example subject:** iOS Crash Log: Crash on launch #111
  * **Example subject:** iOS Crash Log: Crash when sending video #222
