### ISSUE TITLE
Iphone 6 doesn't generate the key

### ISSUE THREAD

**Issue by gbanegas** [WhisperSystems/Signal-iOS#1048]
Hi, 
I am using Signal in an Android phone. However, when some friend of mine that use iphone 6 install Signal, my friend is able to send messages to me but the opposite no. 
When I try to verify the identity of my friend I receive this message: "Recipient has no identity key."

**Comment by Coecoenut** [comment]
I can confirm this (both devices running Android).
However, a friend of mine (also Android) CAN send messages, and view the key of the other person.

**Comment by michaelkirk** [comment]
@coecoenut - it's not clear how an iOS device is involved in your setup. Can you clarify - who is using iOS in your scenario?

**Comment by Coecoenut** [comment]
@michaelkirk There is indeed no iOS device involved. To make it clear:

There are three devices involved, A, B and C.
I (device A) can communicate with others using Signal. I cannot send encrypted Signal messages to one specific device (device B). A friend of mine (device C) can communicate with device B.

Device A can send messages to C, but not to B. It can also view the key of C, but not B.
Using device B, one can view the keys of device C and A and send messages to them.
Using device C, one can view the keys of A and B and send messages to both.
Everyone is using Signal on Android.
It seems that the bug is not limited to a setup with an iOS device, thats why I did not create a new issue but used the existing one.

**Comment by michaelkirk** [comment]
FYI This is the signal iOS tracker, would you mind posting this in the
android tracker? https://github.com/WhisperSystems/Signal-Android

**Comment by michaelkirk** [comment]
@gbanegas if this is still an issue with the latest Signal-iOS could you have your friend submit a debug log?

**Comment by gbanegas** [comment]
@michaelkirk  I will check. If it happen again I put the logs here or open a new issue! 
Thank you :)
