### ISSUE TITLE
Erroneously Listed Contacts. Bloom Filter Update Failure.

### ISSUE THREAD

**Issue by signalanon** [WhisperSystems/Signal-iOS#1101]
Unable to refresh the bloom filter to remove the erroneously listed contacts, or the Bloom Filter has inaccurate entries.

The erroneously listed contacts do not have any version of open whisper apps installed.  Some are even for landline contact numbers. The number of erroneous contacts has increased over time.

I deleted the account in the IOS app, reinstalled, and encountered the same issue with the same erroneous contacts.  Several GBs of available space on the phone, and followed the steps to update the bloom filter on multiple occassions with no success (http://support.whispersystems.org/hc/en-us/articles/212743488-Why-are-my-contacts-different-colors-in-my-contact-list-).

Also unable to connect to a friend that has Signal on android.  The blue phone does not appear next to his name.

**Comment by riyapenn** [comment]
Bloom Filter will be removed: https://github.com/WhisperSystems/Signal-iOS/issues/1028, https://github.com/WhisperSystems/Signal-iOS/commit/26f9207cab06e4df4af3dc9c02deca3d250eb4ae

**Comment by signalanon** [comment]
Thank you! @riyapenn

**Comment by byeskille** [comment]
What is the status of the fix for this? 

The amount of such erroneously listed contacts have reached a high number for several users. It is now a problem when teaching not tech savvy users to use Signal as they get confused about the UI.

And "bloom filter removed"? What will it replaced with? This blog post was a good description of how Signal do contact look up by bloom filter without compromising the entire contact list.. https://whispersystems.org/blog/contact-discovery/
