### ISSUE TITLE
compose text field should have max height.

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1186]
### Bug description

When I enter a really long message, the text field just keeps growing, covering the entire screen. At some point this prevents you from seeing the thread content, which is how you would, in theory, scroll to dismiss the keyboard.

This is especially problematic if you're composing a long response to someone who is simultaneously sending you messages.You won't be able to see what they said until you either send or delete your draft. Or if you want to copy/paste something from earlier in the thread.

### Steps to reproduce
- type a long form message. (17 lines on an iphone 6)

**Actual result:** Text area grows to fit each line, until it covers the entire interface.
**Expected result:** Text area grows up to a point, then utilizes scroll bar to review content, keeping visible at least some of the thread interface.

### Screenshots

![image](https://cloud.githubusercontent.com/assets/217057/15303473/d874e940-1b6c-11e6-8d3d-0fd3b3a839f5.png)

### Device info
**Device**: iDevice 6
**Signal version:** 2.2 and HEAD(4537324fe5bcf2ea4ccc47e214d56aba8c5f2b64)

**Comment by big-r81** [comment]
we can define a maximal height with 
`[self.inputToolbar setMaximumHeight: 150];`
but than we have ugly behavior on delete. In your example try to delete your numbers with backspace...

@FredericJacobs maybe it is a good idea to update your fork of JSQMessageViewController because we are about some commits behind the original source.
