### ISSUE TITLE
App crashes immediately upon opening. 

### ISSUE THREAD

**Issue by boyle3000** [WhisperSystems/Signal-iOS#1214]
### Bug description
The app crashes immediately upon opening. It shows the blue screen with the logo for one second and then disappears. The signal app icon still updates the number of unread messages. This happened after updating to the latest version of signal from the appstore (2.3.1). It happened for both ios versions 9.2 and 9.3.. This bug affected two independent iPhone users. For one it was resolved by reinstalling the app. The other is still waiting for a fix to avoid loosing history. 

We tried:
- turn on phone on and off
- turn on flight mode
- soft reboot
- free memory

### Steps to reproduce
- open app

**Actual result:** App crashes before showing messages.
**Expected result:** App opens.

### Device info
**Device**: iPhone 6
**iOS version**: 9.3.2
**Signal version:** 2.3.1

**Comment by FredericJacobs** [comment]
I had a friend who reported this to me too.

**Comment by michaelkirk** [comment]
@boyle3000 if you or your friend are interested in signing up for our Beta release, contact  support@whispersystems.org.

https://whispersystems.discoursehosting.net/t/call-for-ios-beta-testers-email-support-to-sign-up/349

Also, if you have XCode installed, or are willing to install it, you could extract a crash report, which would help us fix this. Ditto for your friend @FredericJacobs.

**Comment by FredericJacobs** [comment]
@michaelkirk Re-installed the app because had urgent discussions to do.

**Comment by big-r81** [comment]
Hi,

installed the current (965261f) HEAD the app crashes immediately upon opening.

It crashes at ContactsManaer.m at line 282:

**`return [[Contact alloc] initWithContactWithFirstName:firstName
                                             andLastName:lastName
                                 andUserTextPhoneNumbers:phoneNumbers
                                                andImage:img
                                            andContactID:recordID];`**

The Xcode output:

`2016-06-15 12:49:29.741 Signal[1734:1249314] iRate verbose logging enabled.
2016-06-15 12:49:29:747 Signal[1734:1249314] WebSocket is already connecting
2016-06-15 12:49:29.999 Signal[1734:1249314] iRate did not prompt for rating because the app was first used less than 15 days ago
2016-06-15 12:49:30.113 Signal[1734:1249398] -[Contact initWithContactWithFirstName:andLastName:andUserTextPhoneNumbers:andImage:andContactID:]: unrecognized selector sent to instance 0x15f85d640
2016-06-15 12:49:30.114 Signal[1734:1249405] -[Contact initWithContactWithFirstName:andLastName:andUserTextPhoneNumbers:andImage:andContactID:]: unrecognized selector sent to instance 0x15e74b350
2016-06-15 12:49:30.116 Signal[1734:1249398] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Contact initWithContactWithFirstName:andLastName:andUserTextPhoneNumbers:andImage:andContactID:]: unrecognized selector sent to instance 0x15f85d640'
*** First throw call stack:
(0x181d92db0 0x1813f7f80 0x181d99c4c 0x181d96bec 0x181c94c5c 0x10011ee1c 0x10011e770 0x100503ff0 0x10011e420 0x10011ce5c 0x10011c84c 0x100ec1a7c 0x100ec1a3c 0x100ed0c9c 0x100ed0364 0x1819f5470 0x1819f5020)
libc++abi.dylib: terminating with uncaught exception of type NSException
2016-06-15 12:49:30.116 Signal[1734:1249405] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Contact initWithContactWithFirstName:andLastName:andUserTextPhoneNumbers:andImage:andContactID:]: unrecognized selector sent to instance 0x15e74b350'
*** First throw call stack:
(0x181d92db0 0x1813f7f80 0x181d99c4c 0x181d96bec 0x181c94c5c 0x10011ee1c 0x10011e770 0x100503ff0 0x10011e420 0x10011ce5c 0x10011c84c 0x100ec1a7c 0x100ec1a3c 0x100ed0c9c 0x100ed0364 0x1819f5470 0x1819f5020)
libc++abi.dylib: terminating with uncaught exception of type NSException`

and the crash log from the iPhone:
[Signal  15.06.16, 12-48.crash.zip](https://github.com/WhisperSystems/Signal-iOS/files/315984/Signal.15.06.16.12-48.crash.zip)

FYI - I updated my pods before opening Xcode!

Cheers Ronny

**Comment by michaelkirk** [comment]
@big-r81 how repeatable is this? 

Before reverting https://github.com/WhisperSystems/SignalServiceKit/commit/32a7d49facdb26238f13c7e4932a5c7874608a47 was it crashing 100% of the time? 50% of the time? If you re-apply the commit does your app start crashing again? 

There is a [conditional around that method definition](https://github.com/WhisperSystems/SignalServiceKit/blob/master/src/Contacts/Contact.m#L13), *but* it should be satisfied on your device.

**Comment by boyle3000** [comment]
@michaelkirk Thanks for looking into it.

Unfortunately I do not own an iPhone and I think my friends would prefer the stable version. But thanks for the offer.

**Comment by big-r81** [comment]
@michaelkirk 
it is crashing all the time, so the crash rate is at 100% ;-)

I removed the pods and reinstalled it, discard all changes.

But something is really strange:

The crash occurs at my iPhone6 and the iPhone6-Simulator, but
if i choose the iPhone4s and iPhone5 profile, i get 94 compiler errors...

**Comment by michaelkirk** [comment]
>  The other is still waiting for a fix to avoid loosing history.

@boyle3000 - It would be great if this user could test out a potential fix. We have several crash-bug fixes coming in the next pre-release. If they/you are interested in getting this resolved sooner, contact support@whispersystems.org to sign up. More details here: https://whispersystems.discoursehosting.net/t/call-for-ios-beta-testers-email-support-to-sign-up/349

**Comment by big-r81** [comment]
Hi @michaelkirk, 
any new status about this? i can't run the dev version on my phone or in the simulator 🚬

**Comment by michaelkirk** [comment]
@big-r81 Can you see if you are able to run the latest Beta (2.3.2.1) on your phone?

**Comment by big-r81** [comment]
@michaelkirk 
the latest Beta (2.3.2.1) is on my Phone and is working...

**Comment by michaelkirk** [comment]
@big-r81 I think you are experiencing the same symptom (crash on start) from a different root cause, likely a problem in your local build configuration. Trying cleaning all the things `rm -r Pods/`, `pod install`, clean your build in XCode, burn some incense, etc.

**Comment by big-r81** [comment]
@michaelkirk 
nope, i deleted (locally) my fork and did a fresh git clone of my fork.
pod install...
In Xcode Clean
same result...

**Comment by michaelkirk** [comment]
Try to build from the 2.3.2.1 tag. That's what the beta was built from. If
that doesn't immediately crash, it's a local config problem.

**Comment by big-r81** [comment]
@michaelkirk 
burning a lot of incense!
Now it works again. It seems that in the XCode cache was something wrong.

Only for information purpose for other users:

1. run `pod cache clean --all`
2. delete `rm -rf ~/Library/Developer/Xcode/DerivedData/`
3. cleaning `/var/folders`

**Comment by wark88** [comment]
I have been having this same problem for about a month.. Just installed the new update hoping I would be able to use the app finally.. Still crashes immediately upon open..

iPhone 5
iOS 8.1.2

**Comment by michaelkirk** [comment]
Hi @wark88

This particular symptom could be caused by several different issues, but we're making our way through them. If you're willing to install XCode to get a crash log off your device we could better fix the issue you're having. LMK if you're interested and I can walk you through it.

**Comment by michaelkirk** [comment]
Just an update: Crashing on boot is a symptom that could potentially have multiple causes. For the crash reports we've been able to collect from users reporting crashing-on-boot, we've found a recurring pattern of ios8.0/8.1 users who end up with a corrupted database. 

The data I have shows that 95% of crashes from a corrupt Signal DB are coming from ios8.0/8.1 users, while that same group of users only accounts for 1% of our overall user base. Though updating to a newer version of iOS is likely to prevent this corruption, it's unlikely that updating will fix an already-corrupted database.

If you are an iOS8.0/8.1 user whose device is crashing on boot and are interested in helping debug this, let me know and I can put together a debug build to get better data from your device. Without that, it's unlikely that this will be resolved.

Otherwise, the expedient "solution" would be to remove and reinstall the app. Be advised with this route you'll lose all message history and any group threads that you are currently in will need to be updated before you'll receive messages in them.

**Comment by Alastiran** [comment]
@michaelkirk I'm running 8.1 and getting 100 % crashes on startup. What do I have to do to help get data with a debug build? I have some experience developing iOS, but not much in migrating client data stores.

**Comment by michaelkirk** [comment]
@Alastiran can you contact me at michael@whispersystems.org and I'll follow up with getting you a debug build there.

**Comment by michaelkirk** [comment]
To anyone still experiencing this issue, please contact support@whispersystems.org with the subject "App Crashing on Boot #1214: Sign me up for the Signal iOS Beta".

If the new build allows you to boot, please consider submitted a debug log so that we can have a more fine grained understanding of what went wrong.

**Comment by riyapenn** [comment]
Old issue unrelated to iOS 2.5.1.  Please update to Signal 2.5.2 which is in the iTunes Store here: https://itunes.apple.com/us/app/signal-private-messenger/id874139669?mt=8  Email support@whispersystems.org if there are issues with Signal 2.5.2.

**Comment by Synchro** [comment]
FWIW, I was having the same issue with 2.5.1 on a 5S with iOS 10.0.1 and delete/reinstall fixed it. The crash it was logging related to the database.
