### ISSUE TITLE
Launching fullscreen media view should require tapping directly on media bubble

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1257]
### Steps to reproduce
- receive attachment
- tap on white space horizontally adjacent to attachment

**Actual result:** Fullscreen media view opens
**Expected result:** Fullscreen media view should only open if you click *on* the media bubble.

**Comment by gluxon** [comment]
This appears to be the line causing the issue.

https://github.com/WhisperSystems/Signal-iOS/commit/4d320d60150f04a4e6234ca2a3b5ccca58a49356#diff-cdc353260e006d747b55ce6d90702e1dR1041

I'd like to do a pull request, but I would be concerned that deleting the line breaks something else. What's the reason `didTapMessageBubbleAtIndexPath` is being called by `didTapCellAtIndexPath`?

**Comment by michaelkirk** [comment]
I believe it's there to support tapping on info/error messages.

e.g. The "key changed" dialog.

**Comment by gluxon** [comment]
Ah. I assumed the comment was referring to internal debugging info/error messages. Thanks for the quick response.

**Comment by big-r81** [comment]
@michaelkirk 
Hi,
on my device (iPhone 6, iOS 9.3.2, Signal 2.3.5) there is no such a problem.

it seems that this was introduced after Signal 2.3.5 ...

**Comment by michaelkirk** [comment]
> it seems that this was introduced after Signal 2.3.5 ...

That's likely, a lot of code moved around in the recently merged #1255

**Comment by gluxon** [comment]
Yeah, the line I linked to was introduced a few days ago. So the root of the issue is that Signal's subclassed `JSQMessageCollectionViewCell` has no `messageBubbleContainerView` property for info and error messages. JSQMessages relies heavily on that for bubble tap math. The workaround is to just add a check in the `didTapCellAtIndexPath` to only call `didTapMessageBubbleAtIndexPath` for those messages.

I'm going to try getting `OWSDisplayedMessageCollectionViewCell` properly subclass. If that introduces too many errors, I'll use the workaround.

**Comment by michaelkirk** [comment]
Thanks for look @gluxon. As this is a new regression, it will have to be fixed soon before the next release can go out. I'm conceptually in favor of being able to use the default bubble sizing, if it is straight forward enough and means we can avoid hacks like this: https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/Models/OWSMessagesBubblesSizeCalculator.m#L27

But if not, I'll just merge in something like this: https://github.com/WhisperSystems/Signal-iOS/tree/fix-tap-directly-on-media-cell%231257

**Comment by michaelkirk** [comment]
closed in #1260
