### ISSUE TITLE
Fix "Accept (null)'s new Identity Key?"

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1276]
When a user who is not in you contact changes their key, we get a confusing error message.
## Steps to reproduce
- Squirrel has Raccoon in her address book, but not vice versa
- Squirrel starts a group thread, adding Raccoon to the group.
- Squirrel sends a message in the group thread to Raccoon. "hi"
- Raccoon sees the message "hi" from Squirrel's phone number (+15551231234)
- Squirrel reinstalls Signal (changing her key)
- Squirrel sends another message in the group thread to Raccoon. "hello"
- Raccoon sees "Identity Key Changed. Tap to verify." warning message
- Raccoon taps the warning message

**actual result**
Raccoon sees "Do you want to accept (null)'s new Identity Key"

**expected result**
Raccoon sees "Do you want to accept +15551231234's new Identity Key"

I'm not sure how well that will localize. But it can't be worse than "null".

_hint_ this should be done not at the point of printing the alert, but in the method which translates  identifiers to contact name (and similar code refactored appropriately)

**Comment by ajstiles** [comment]
I am unable to replicate the bug following the steps outlined above. Here's more detail on what I did:

## Steps to reproduce
* Squirrel is my phone
* Racoon is my development environment/XCode/simulator
* Racoon has verified a phone number via Twilio programmable SMS, a different phone number than Squirrel
* Squirrel has Raccoon in her address book, but not vice versa
* Squirrel sends a message to Racoon. "hi"
* Racoon sees the message "hi" from Squirrel's phone number (+15551231234)
* Squirrel reinstalls Signal (changing her key) and verifies original phone number
* Racoon sees "Identity Key Changed. Tap to verify." warning message
* Racoon taps the warning message

**actual result**
Racoon sees "Do you want to accept +15551231234's new Identity Key"

Poking around MessagesViewController.m, [handleErrorMessage method L1397](https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/view%20controllers/MessagesViewController.m#L1397), the code checks if message is a instance of TSInvalidIdentityKeySendingErrorMessage class. That check is failing because message is an instance of TSInvalidIdentityKeyReceivingErrorMessage class. When the check fails, keyOwner is derived from the thread name, which is the correct sender phone number.

It seems that the hint would want us to change OWSContactManager nameStringFromPhoneIdentifier method so that it returns the value of the identifier passed into the method instead of nil when there's no matching contact found.

Thoughts on how to proceed? Perhaps there's another step to replicate the issue? I thought that it might require Raccoon to send the second message rather than Squirrel, but Raccoon doesn't have Squirrel in her address book and can't send a message.

**Comment by michaelkirk** [comment]
You're right @ajstiles. I left out a precondition that I didn't realize was necessary - it must be a group thread for this to occur.

I've updated the description. Thanks!

**Comment by ajstiles** [comment]
Thanks for the update @michaelkirk.

I'm still having trouble replicating. In my case, Squirrel is my phone and Raccoon is running in the emulator via XCode. Re-installing Signal on Squirrel requires uninstalling Signal, then installing again, which blows away Squirrel's prior record of the group thread. When Squirrel creates the new group thread with Raccoon, Raccoon sees the "Identity Key Changed..." message before Squirrel has a chance to send the followup "Hello" message. Squirrel's correct phone number is displayed in the "Do you want to accept..." message.

I've tried a few ways, including having Raccoon delete the original group threads after Squirrel uninstalls, and leaving them intact. That doesn't seem to make a difference.

**Comment by nixnuex** [comment]
I agree with @ajstiles, I'm also not able to reproduce this bug. When I perform the steps described above (based on a group chat), I receive the "Identity Key Changed..." message including the number (not nil) before anything else. Which detail are we missing here?

**Comment by michaelkirk** [comment]
I'm no longer able to reproduce this either. But I'm not sure how it would have been fixed... Closing for now.
