### ISSUE TITLE
[feature request] Message Timers

### ISSUE THREAD

**Issue by caveman1973** [WhisperSystems/Signal-iOS#1279]
I know there is no guarantee the message will be deleted from the recipient's device but Implementing a message timer would be very useful under certain situations:

- Lets say you're communicating in an hostile environment and you get caught by some adversary. Having a timer, you'll know that when forced to reveal the content of your chat, the message will already* be deleted from your device.
* If you established a correct timer.

Same apply to the recipient. You know _your_ messages won't be available inside the recipient's device when caught by some adversary.

**Comment by caveman1973** [comment]
https://github.com/WhisperSystems/Signal-iOS/issues/254

**Comment by michaelkirk** [comment]
dupe of https://github.com/WhisperSystems/Signal-iOS/issues/254

**Comment by caveman1973** [comment]
Actually it is not the same. #254 means to delete old messages after certain amount of messages, not under certain specified amount of time.

I'm suggesting the same feature as Telegram or Wickr.

**Comment by campingisintents** [comment]
This is an essential, yet missing feature. The best way to analogize this would be to talk about like Google's inactive account manager. After a certain period of time of the app/device not being used, a message would *then* automatically be deleted. Otherwise, if the person continues use of app, no auto delete for older messages. The importance of this time-based deletion policy cannot be overstated for unapproved searches and/or seizures of devices for local attacks.
