### ISSUE TITLE
Fingerprint description in privacy settings

### ISSUE THREAD

**Issue by PanosSakkos** [WhisperSystems/Signal-iOS#1295]
- [x] I have searched open and closed issues for duplicates

---
### Bug description

How about adding a footer explaining what the Fingerprint is to the user?
### Steps to reproduce
- open settings
- tap on Privacy

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
### Screenshots

![img_1623](https://cloud.githubusercontent.com/assets/1270063/17258847/1c42a7de-55c9-11e6-9e0c-283e3ef12e9d.jpg)

**Comment by naomihimley** [comment]
Is there suggested copy for what this might be?

**Comment by Calefornia** [comment]
Explaining the fingerprint in terms of a unique identifier (like your own physical fingerprints!!) is the simplest and most straightforward way. People want to be sure they're communicating with the right person, and a fingerprint uniquely identifies them. This is addressed in an [FAQ post](http://support.whispersystems.org/hc/en-us/articles/213134107-How-do-I-verify-the-person-I-m-sending-messages-to-is-who-they-say-they-are-):

> Each Signal user has a unique fingerprint, and these fingerprints get stored the first time you exchange a private message with a new contact. You will be warned if a user's fingerprint ever changes...."Your identity" on your phone should match the identity key for your name on your contact's phone, and "Their identity" on your phone should match the identity key on theirs....If the fingerprints are identical then you can be sure that you are communicating with the right person."

**Comment by naomihimley** [comment]
ok that is very long and will look like this. I can open a PR with this if people think this looks ok, but we will also need another bug for the translations of that for all the localization files. 
![screen shot 2016-09-12 at 9 39 46 am](https://cloud.githubusercontent.com/assets/6947424/18442181/0a2fbc7c-78cd-11e6-8276-38ab3960d23e.png)

**Comment by michaelkirk** [comment]
Thanks for the mockup and copy suggestion @naomihimley

Can we put this on ice for a minute? There's a new fingerprint format coming soon, which will invalidate this copy. I'll ping you when it's up for feedback.

For reference, new fingerprint in Android: https://github.com/WhisperSystems/Signal-Android/pull/5646

**Comment by halb9** [comment]
Quick suggestion from my point of view. 

Do not use the term "fingerprint". 

I once had someone came up to me asking how this "fingerprint stuff" works while pointing to the actual fingerprint reader on his mobile phone. 

This made me realise that 'fingerprint' is simply the wrong term to use. 

Here is my problem. Techies use the term fingerprint to describe a string of characters which has to be checked in order to make sure the communication channel is legit and not tampered with. 

But this is not a fingerprint! A fingerprint is a set of lines on your finger making it more or less unique. 
Imagine you don't know the technical meaning of a fingerprint. And you where asked to verify your contact via fingerprint. How the hell do you do that? 

Furthermore this is counterintuitive. The fingerprint on your device might change. Your actual fingerprint does not. 

And I would like to add. I'm not sure how the word fingerprint translates into other languages. In english it obviously remains the same. 
In Germany we don't really use the translation when talking about verification. We don't check the "Fingerabdruck". Wir überprüfen den Fingerprint. English word in a german sentence. 
If you think about localisation of the app. You have two options. Keeping the term fingerprint. Or translate it. Both options are not ideal because you might end up either with a translation where the translation doesn't even make sense. Or you keep the word fingerprint but the user does not know the term fingerprint because it is not his native language and is clueless of what to do. 

Therefore I might suggest a more general naming approach like "Device Identity Key" or something like that. 
This is a far more straightforward explanation of what it really is. The identification of a device. Not your friend. Not your wife. You don't check the fingerprint of your girlfriend. You check the Identity Key of the device of your girlfriend. 
This makes it as well easier to translate. 

And you can get rid of all the explanation of what a fingerprint is. Like moxie said, a user doesn't need to know what a fingerprint is. 
Just check the damn Identity Key of the device you're communicating with. And if it's fits, you're good. 
If it doesn't you can prompt the user with more information what this means and what he/she should do in that case. But not before. 

Oh this applies to Android as well of course. 

Thanks for reading! Have a nice day!

**Comment by sweeper3000** [comment]
@halb9 Actually, if you take a look at the Android repo, in the strings.xml file, you'll see that Moxie is calling them "safety numbers" That string can be found in the PR on the Android repo that was mentioned above. So obviously, it would make sense that the change is reflected here.

**Comment by FeuRenard** [comment]
In this post you can find screenshots of the new "fingerprint" implementation in Android:
https://github.com/WhisperSystems/Signal-Android/pull/5664#issue-174926579

**Comment by riyapenn** [comment]
Closing as [Safety Numbers](https://whispersystems.org/blog/disappearing-messages/) are per conversation. Additional info available on the [support page](http://support.whispersystems.org/hc/en-us/articles/213134107-How-do-I-verify-the-person-I-m-sending-messages-to-is-who-they-say-they-are-).
