### ISSUE TITLE
Signal doesn’t start

### ISSUE THREAD

**Issue by maltemayer** [WhisperSystems/Signal-iOS#1302]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
App doesn’t start. Similar to #1214 but the start screen stays like for 20 seconds before the App crashes. I can’t find any for crash report for Signal though.

### Steps to reproduce
- Start app

**Actual result:** App stays in the start screen and eventually crashes.
**Expected result:** Tha App should open normally.

### Device info

**Device**: iPhone 5
**iOS version**: 9.3.4
**Signal version:** 2.4.1.0 beta

**Comment by michaelkirk** [comment]
Thanks for the feedback.

It sounds like a startup task is taking too long to run. This could be due to some changes in the 2.4.1.0 beta that cleans up old attachments on launch. Feel free to go back to the app store and install the latest stable version until there is a new beta version out. I don't think that should cause any troubles in your case.

>  I can’t find any for crash report for Signal though.

In case you didn't already follow these instructions, this is where they would appear: https://github.com/WhisperSystems/Signal-iOS/wiki/Submitting-crash-report#to-submit-your-crash-report

**Comment by michaelkirk** [comment]
It's hard to say *exactly* what's causing your problem, but I've done some work to make 2.4.1 launch faster in #1303 - it will be in the next beta release, coming soon.

**Comment by michaelkirk** [comment]
I just released Beta 2.4.1.1. Can you give it a try and let me know if it fixes your problem @maltemayer?

**Comment by maltemayer** [comment]
Thank you for the fast response.

It crashed again but worked fine after the second try and I have no trouble since then.

In the current App Store release (2.4) messages written to yourself are retrievable after the deletion of the threat. All you have to do is open the threat again by composing a message. This is fixed now with Beta 2.4.1.1.

> In case you didn't already follow these instructions, this is where they would appear: https://github.com/WhisperSystems/Signal-iOS/wiki/Submitting-crash-report#to-submit-your-crash-report

I did that of course, but there are no crash reports named in that format.

**Comment by michaelkirk** [comment]
@maltemayer would you mind submitting a debug log? (Settings > Advanced > Submit Debug Log) 
(and checking again to see if any crash reports have yet been generated)

You can email any or either to michael@whispersystems.org
