### ISSUE TITLE
Disabling the sound while sending a message

### ISSUE THREAD

**Issue by ceving** [WhisperSystems/Signal-iOS#1373]
The App generates a sound whenever I **send** a message (outgoing communication). The App has no option to stop this sound. The only option is to mute the hole phone.

**Comment by lazerwalker** [comment]
Hey! I'm interested in jamming on this, but have a quick question about design. 

The "Notifications" settings screen already has the option to enable/disable incoming notification sounds. I'd assume a sensible implementation of this would involve ripping out that settings option and creating a single consolidated "Sounds" setting option.

Is maintaining separate toggles for the different types of in-app sounds (incoming notifications, outgoing messages, etc) necessary, or is just having a single "Sounds on/off" toggle acceptable? My instinct would be that a single toggle is acceptable for a first stab, but wanted to make sure before I invest time on this.

(Also, if this is a discussion better meant for the community Discourse, my apologies!)

**Comment by michaelkirk** [comment]
Great.

I think the existing toggle should stay as is, rather than having more options, and we should be respecting that setting when playing the "sent message" notifications.

**Comment by lazerwalker** [comment]
To clarify: the current toggle lives within the "Notifications" settings sub-screen, and is currently labeled "Notification Sounds". Your suggestion is that the current settings taxonomy stay exactly the same, but the behavior changes so that the "sent message" sound also respects that "Notification Sounds" toggle. Correct?

My worry is that someone trying to disable all in-app sounds is not going to think to look in the "Notifications" section. My instinct is that it would be less confusing to move that option, so instead of living within the "Notifications" screen, there's e.g. a menu option directly on the top-level settings screen that has a slide toggle on it. The label would presumably be something like "In-App Sounds". 

I'm not honestly sure my suggestion is better — I agree adding more top-level options is less than ideal — but I do still worry about that discoverability issue.

**Comment by michaelkirk** [comment]
Yeah, it's a little tricky to know which will surprise the least number of users.

> My worry is that someone trying to disable all in-app sounds is not going to think to look in the "Notifications" section.

I don't think we want a "disable all in-app sounds" toggle, e.g. if I play a video, I expect to hear noises wether or not this switch is enabled. 

I think leaving it in notifications makes the most sense.

**Comment by lazerwalker** [comment]
Yeah, makes sense. I'm not completely sold that's the least-surprising place for it, but you surely know your users better than I do, and I don't want to let the perfect be the enemy of the good. PR opened! (#1433)

**Comment by michaelkirk** [comment]
fixed in https://github.com/WhisperSystems/Signal-iOS/commit/7c6b84c46b53a49f15604da348a807df6be3f5ad. Thanks @lazerwalker!

**Comment by Del419** [comment]
1. In Signal, tap your profile profile_avatar.png > Notifications.
2. Tap Play While App is Open to manage the sound you hear each time you send a message
3. To enable, tap the slider so it is blue.
You may need to adjust your phone's silent/vibrate switch to Ring mode so that the orange is not showing. See Apple's support page.
4. To disable, tap the slider so it is grey.

**Comment by laurgao** [comment]
Thank you for this

**Comment by snan** [comment]
> Tap Play While App is Open to manage the sound you hear each time you send a message

I still wanna hear when I *receive* a message? 🤔
