### ISSUE TITLE
Incoming media preview is cropped but not scaled

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1383]

**Comment by ngheungyu** [comment]
+1 thanks

**Comment by roostr** [comment]
I'm looking into this one.

**Comment by roostr** [comment]
Is anyone able to confirm that I have correctly identified the expected results/actual results failure sitation?

After some experimentation, here's what I've found:

1. Very high megapixel images with a typical aspect ratio (less than 2:1 or 1:2), both message thread inline preview (MTIP) and the fullscreen result you get when you tap on it behave exactly like I would expect. ✅
2. Furthermore, for all standard aspect ratio images (such as 4:3, 3:4, 16:9, 9:16), everything works exactly as I would expect. ✅
3. For abnormally stretched aspect ratio images (10:1, 1:10), the message bubbles never exceed a certain aspect ratio (eyeballing it, the chat bubble aspect ratios top out at about 2:1 or 1:2). Rather than showing the whole image in the MTIP, which would require either letter-boxing the image with black borders on either side or supporting very elongated message preview bubbles, the chat bubble crops the image to be just the amount that will fit within the message preview area. So to show a 10:1 image in a 2:1 chat bubble, for example, it only shows the inner 20% of the image, and crops out the 80% that doesn't fit. ❓

- Is #3 a correct description of the failure case?

Here are some images to make the discussion concrete. Given these two images:

![tall](https://cloud.githubusercontent.com/assets/978146/20503533/ec0f188e-b010-11e6-8835-3321f0323d33.png)
![wide](https://cloud.githubusercontent.com/assets/978146/20503535/f02a328c-b010-11e6-81bc-4d0006b40979.png)

This is how the message thread inline preview is rendered in Signal:

![img_8979](https://cloud.githubusercontent.com/assets/978146/20503659/b54018f2-b011-11e6-9a44-48a8a0ce02aa.PNG)

![img_8980](https://cloud.githubusercontent.com/assets/978146/20503664/b9e9337a-b011-11e6-8368-2d3c2866b2cf.PNG)

And this is how the message thread is rendered in iMessage on iOS 10.1.1:

![img_8981](https://cloud.githubusercontent.com/assets/978146/20503666/bf60103a-b011-11e6-9d2a-eaf9da56c9c1.PNG)

Note that on iOS, the message bubbles can contort to large aspect ratios, but they also have limits. The vertical preview maxes out at about 1:6, and the horizontal preview maxes out at about 5:1. After that, they behave the same way as signal (showing the center, cropping edges that don't fit into the preview area). So if the goal would be to match iMessage, then we would just extend bubbles to allow higher aspect ratios.

I'd like to get feedback on what we should do next, as it seems the upstream library is behaving as designed. If we change anything, I would recommend allowing higher aspect ratios, closer to 1:6/5:1 like iMessage does. This may require forking JSQMessageViewController. Thoughts?

**Comment by michaelkirk** [comment]
My fault for not including screenshots when I opened this issue.

I can no longer reproduce the issue that I was experiencing. I think the actual behavior may have been inadvertently solved by the recent https://github.com/WhisperSystems/Signal-iOS/pull/1407

Prior to that, high resolution incoming thumbnails were being rendered unusably "zoomed in".

Thank you for looking into this.
