### ISSUE TITLE
Recenter/Make wider the invite flow's search input field

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-iOS#1516]
- [X ] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Expand search field width and recenter (extra space to the right)

### Steps to reproduce
- Signal Message Compose
- Choose Invite Friends to Signal
- Choose Message or Mail

### Screenshots

![signal contat picker](https://cloud.githubusercontent.com/assets/4898366/20818293/80b64778-b7e1-11e6-8144-65bf45639619.jpeg)

### Device info

**Device**: iPhone 5C and iPhone 6S
**iOS version**: 10.1.1
**Signal version:** 2.6.6

**Comment by michaelkirk** [comment]
I believe this is due to the width of the section index (the vertical A-Z), which actually extends through the search row (with a transparent background). The search bar is then being centered WRT to the left edge of the section index.

So a solution might be offsetting search by 1/2 the section index width.
