### ISSUE TITLE
TS

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#156]

**Comment by BoerenkoolMetWorst** [comment]
I've been testing it for a few days, and I really like the new GUI. It's stylish but intuitive and calling+message functionality isn't confusing. I also like the animation when for example pressing the attachment button. It gives the app a more professional, finished feel instead of a wacky open source project. Thanks to all who contributed! :)

One question: Will there be some indication in the GUI when fingerprints are verified? For example, perhaps change the color of the padlock in conversation view to green or put a checkmark somewhere. Then there should also be a Mark as verified button, in case manual verification is done instead of scanning.

**Comment by FredericJacobs** [comment]
@BoerenkoolMetWorst Fingerprint format is going to change and such an indication in the UI would be really useful indeed.

**Comment by generalmanager** [comment]
@FredericJacobs  @BoerenkoolMetWorst We discussed the options to implement this over in the TS github in some depth: https://github.com/WhisperSystems/TextSecure/issues/910

**Comment by moxie0** [comment]
If anything I'd like to go in the opposite direction and eliminate the ability to view fingerprints outside of a TOFU mismatch at all.  I'm willing to leave it accessible if subtle, but don't want to surface trusted/untrusted in the UI.

**Comment by corbett** [comment]
@abolishme could you comment on the current beta with the following (focusing on getting the UX consistent with your vision not necessarily pixel perfect

UX:
must have for 2.0 (first launch of Signal w/TextSecure functionality)
nice to have for 2.0
ok to push to 2.1 (first update) or 3.0 (first major update w/"perfect" UX)

UI:
must have for 2.0 (first launch of Signal w/TextSecure functionality)
nice to have for 2.0
ok to push to 2.1 (first update) or 3.0 (first major update w/"pixel perfect" UI)

/cc @moxie0 @mcginty @FredericJacobs
