### ISSUE TITLE
Leaving a group disables disappearing messages for Desktop users in the group

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1566]
Moved/modified from https://github.com/WhisperSystems/Signal-Android/issues/5996#issuecomment-269436851

## Bug description

When an iOS user leaves a group, the disappearing messages setting is turned off for the remaining Android members of the group.

## Steps to reproduce

- Alex Android and Irma iOS are in a group with disappearing messages. 
- Both are linked to Desktop.
- When Irma leaves the group

Alex's Android device show "Irma left the group" (disappearing messages are still enabled)

And...
**Actual result:** Alex's Desktop shows "Irma set the timer to off." and "Irma left the group."
**Expected result:** Alex's Desktop shows "Irma left the group" (disappearing messages are still enabled)

**Note:** This could also be fixed in Signal-Desktop by ignoring expiration information for group updates.

**Comment by guillett** [comment]
I put together a fix for that issue, fixing the code in Signal-iOS. The bug comes from the fact that the leave-group message is sent without an expiration time.

I feel like the proper fix should be done in SSK where instead of defaulting expiration time to zero when missing, it should be sourced from the OWSDisappearingMessagesConfiguration if enabled or else be zero.

Let me know what you think is best, I will create a PR in the appropriate project.

**Comment by guillett** [comment]
@michaelkirk Being unhappy with my fix I digged a little bit more and realized that it is a bug of the Desktop app and that my fix in iOS was just hiding the issue. It took a while to get a good set up but I created a PR with the fix there: https://github.com/WhisperSystems/Signal-Desktop/pull/1015

**Comment by nrizzio** [comment]
Fixed in Signal Desktop by 400313f749e65692fccc4f95fcd20d2820534c5d.
