### ISSUE TITLE
censorship circumvention in Cuba, Oman

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-iOS#1576]
Similar to our handling in UAE and Egypt, handle domain fronting in these countries.

**Comment by 2-4601** [comment]
And https://github.com/WhisperSystems/Signal-Android/issues/5992

**Comment by binaryanomaly** [comment]
Please allow a silly question from a curious observer: Why not make it smart and generic? I.e. try direct connection then fallback to AWS, google, ... Domain fronting, etc. Would save you the maintenance and would work seemless for travelling people?

**Comment by 2-4601** [comment]
@binaryanomaly https://github.com/WhisperSystems/Signal-Android/commit/541718fd114a6f2336222a571869e1056cd122dd#commitcomment-20263137

**Comment by riyapenn** [comment]
Cuban number registration fails without a VPN; Signal Desktop works without a VPN. 

<img width="179" alt="screen shot 2017-01-19 at 9 48 42 am" src="https://cloud.githubusercontent.com/assets/4898366/22118467/c2bf3028-de2c-11e6-9065-5545d01ac84d.png">

**Comment by lxmedina** [comment]
The screenshot above was from my device. Log:
`2017/01/18 15:02:06:769  The server returned an authentication failure: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: forbidden (403)" UserInfo=0x1740fc500 {NSUnderlyingError=0x1742511f0 "Request failed: unacceptable content-type: text/html", com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x17023e2e0> { URL: https://google.com.cu/v1/accounts/sms/code/[ REDACTED_PHONE_NUMBER ]?client=ios } { status code: 403, headers {
    "Alt-Svc" = "quic=\":443\"; ma=2592000; v=\"35,34\"";
    "Content-Length" = 1611;
    "Content-Type" = "text/html; charset=UTF-8";
    Date = "Wed, 18 Jan 2017 20:02:06 GMT";
} }, NSErrorFailingURLKey=https://google.com.cu/v1/accounts/sms/code/[ REDACTED_PHONE_NUMBER ]?client=ios, com.alamofire.serialization.response.error.data=<3c21444f ...`

1. Have you at Signal tested that the Cuban (one and only) ISP is actually censoring Signal?
2. Lots of US services do block accesses from Cuban IPs due to US sanctions/embargo. Google Cloud is one of them. If the frontend server for Signal domain fronting implementation were hosted there, that could be a reason for the 403 error above.

Glad to help/test anything from here. Keep up the great work!

**Comment by michaelkirk** [comment]
@lxmedina - Thanks. If you have time for some testing, email me at michael@whispersystems.org.

**Comment by lxmedina** [comment]
@michaelkirk Sure... email sent!

**Comment by michaelkirk** [comment]
Fixed in #1626

**Comment by riyapenn** [comment]
Omani user stating this is an issue: https://gist.github.com/anonymous/5691aadc934c3ddf7775814c4b5ade41

**Comment by michaelkirk** [comment]
> On Mar 2, 2017, at 7:52 PM, riyapenn <notifications@github.com> wrote:
> 
> Omani user stating this is an issue: https://gist.github.com/anonymous/5691aadc934c3ddf7775814c4b5ade41 <https://gist.github.com/anonymous/>
> 


Is the Omani user able to call? or send messages? or neither? Do they get any error?
