### ISSUE TITLE
Broken by design or the invented mokeys

### ISSUE THREAD

**Issue by PIXELSTURM** [WhisperSystems/Signal-iOS#1623]
Before last update -> it works @ OSX.
Currently the charming Desktop-Support has gone a few hours ago.

For me it's really hard to understand why this happen. Hey, i am 20-30 years in the business. Java? Really? And incompatibilities after all? Multiplattform? Metaluna? Mars? Watney? Anyone?

Sorry.

Okay it's beta. But there's not any accuse for that...
Keep on ago.

**Comment by 2-4601** [comment]
Dear Sir/Madam,

You are correct. This app is invented by monkeys. I suggest switching to another app immediately.

Personally, I have changed to an app that is invented by three horses (though I suspect one of them is just a donkey but is very good at faking it). In any case, this other app is mostly very good. Only once have I had an issue with it and it got solved after I sent the three horses (or two horses and one donkey who's deviously good at faking it, please see above) a polite feedback saying something like "You fucking bronies, why the app suddenly stopped working, I've been using Rust since the fifties, I'm six foot eight, I have plumpy lips and weigh 61 pounds in Mars. Bubble gum. Portwine. Montauk Project." And just like that the app immediately started working again. I didn't even have to send a debug log, tell how to reproduce the issue or give any info of the device I was using or other such nonsense.

**Comment by michaelkirk** [comment]
What @2-4601 said.
