### ISSUE TITLE
Message sending should fail immediately when not connected.

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-iOS#1743]
Repro:

* Enter airplane mode.
* Send message.

Expected: Message fails immediately.
Observed: Message sending is retried N times, then fails a few minutes later.

**Comment by riyapenn** [comment]
Perhaps, also include UIUX alert indicating not connected to the internet visible to the user prior to/as user types the message and device is offline.

**Comment by footiecrazie** [comment]
@riyapenn, on iOS Apple recommends to make the network call and then handle failure.
https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/WhyNetworkingIsHard/WhyNetworkingIsHard.html#//apple_ref/doc/uid/TP40010220-CH13-SW3
https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW25

@charlesmchen, when in airplane mode i can see 'Sending Failed. Tap to retry' text below the message. In addition the the message background text is greyed out. Observed this behaviour in latest code. Can you please suggest whether this issue is still valid?

**Comment by charlesmchen** [comment]
I've tested a few scenarios and this now appears to be working properly.  I'm closing.
