### ISSUE TITLE
Image/transparent images don't show up in messages view.

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-iOS#1779]
If you receive an image that only has white or transparent pixels, it doesn't show up against the white background of the messages view.

Example image:

![settings_white_thin 2x](https://cloud.githubusercontent.com/assets/625803/23029450/95ebcf4e-f438-11e6-8499-e9f69e683b7b.png)

How it appears:

![screen shot 2017-02-16 at 11 11 03 am](https://cloud.githubusercontent.com/assets/625803/23029462/a292c086-f438-11e6-87e6-d596d08a8531.png)

We could show a classic "grey-white checkerboard" pattern behind images to reveal their location.

**Comment by michaelkirk** [comment]
I feel like people have a transparent background because they don't want it to show. The collateral downside is with white images, as you've outlined here.

But if we *did* implement this as you've suggested, then the downside is that we'd be showing a checkerboard background when some (I'd argue most) people expected it to be transparent. I can't think of an app that does this outside of an image editing program.

**Comment by michaelkirk** [comment]
As per above, I don't think we should change this. Feel free to re-open @charlesmchen.
