### ISSUE TITLE
Swipe right in conversation does not exit anymore

### ISSUE THREAD

**Issue by Ginari** [WhisperSystems/Signal-iOS#1845]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
When in a conversation it used to be possible to swipe right from the left edge of the screen to go back. This is not the case anymore and disrupts the workflow. (Compare to iMessage or Whatsapp)

### Steps to reproduce
- Go into any conversation
- Swipe right from the left edge of the screen

**Actual result:** nothing happens
**Expected result:** should drag the screen, following the finger and "close" the conversation going back to the default screen where all conversations are visible

### Device info

**Device**: iPhone 6s
**iOS version**: 10.2.1
**Signal version:** 2.8.1

**Comment by TempSpas** [comment]
The bug is still present in version 2.8.2, on an iPhone 6.

**Comment by Aktariel** [comment]
Especially galling/finger-cramping on the Plus-sized phones.

**Comment by aliceriot** [comment]
The recent change to the location of the settings button also makes the 'back' chevron a more difficult touch target. Since the 'settings' button is now right next to it I keep accidentally opening the settings when I intend to go back to the thread index. Of course, this is after I try 3-4 times to use the swipe gesture to go back 😂 

fwiw I'm also seeing this issue on version `2.8.2` on a 6s w/ iOS v `10.2.1`

**Comment by ziyaddin** [comment]
Not only in iPhone 6/6s but also iPhone 5s too.

**Comment by m-cerveny** [comment]
What does "Help wanted" mean? Can ordinary mortals help?

**Comment by michaelkirk** [comment]
> What does "Help wanted" mean? Can ordinary mortals help?

Yup. "Help wanted" means both "This is definitely a useful task" and "This is a good task for someone without a ton of context" since some of the other tasks benefit from being familiar with the codebase.

However, the code for this has already been written in #1866, and is just pending code review. I'll remove the label from this issue.

**Comment by michaelkirk** [comment]
Will be released in 2.9.0, thanks!
