### ISSUE TITLE
Contacts are incorrectly shown to be reachable via Signal Video

### ISSUE THREAD

**Issue by kiliankoe** [WhisperSystems/Signal-iOS#1861]
- [x] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description
Every contact on my phone without other means of video contact is shown to be reachable via Signal on the contact sheet. On tapping this button, Signal shows an error that this contact is not a Signal user.

I have enabled `iOS Call Integration` and `Show Caller's Name & Number` in Signal, which I believe might be relevant in this case? Although it also doesn't make a difference for this issue if I disable them.

### Screenshots

![img_6032](https://cloud.githubusercontent.com/assets/2625584/24072956/81893e46-0bef-11e7-8591-9f1f0296a7c2.jpg)

![img_6033](https://cloud.githubusercontent.com/assets/2625584/24072957/854fd3d2-0bef-11e7-87b4-b8787839ddb7.jpg)

### Device info

**Device**: iPhone 6s
**iOS version**: 10.2.1 (14D27)
**Signal version:** 2.8.2

**Comment by michaelkirk** [comment]
Hi @kiliankoe, 

I agree that this is confusing, but I don't think we can fix it.

If you have any other calling apps installed, you can long press on the video button to see those other apps listed - regardless of if the user actually has an account with that app. This is just how the contacts app works. There's no way for us to say "tell contacts app that this user is or is not a Signal user".

If you *do* call this user using a different app (e.g.) LINE, the Contacts app will assume that it's your preferred contact method for that user, and will surface (e.g.) LINE for the top video option instead of Signal.

**Comment by NicolasCGN** [comment]
You could give the option to send an invitation in that dialogue to install Signal. Google Duo does it

**Comment by kiliankoe** [comment]
@michaelkirk Hmm, thanks for the comment. That's unfortunate. I'm going to look through the CallKit APIs for some context and then open a radar about that. I don't see why iOS should basically be lying to the user about their contacts reachable where they're not.

**Comment by NicolasCGN** [comment]
From the Contacts app, you can also place Whatsapp and Duo calls to contacts that are not registered.

Interestingly enough, the Contacts app does know which contacts you can text through Whatsapp and which ones not (not registered).

It would be also nice to have the option of placing Signal messages through the Contacts app.

**Comment by michaelkirk** [comment]
> On Mar 22, 2017, at 17:43, NicolasCGN <notifications@github.com> wrote:
> 
> From the Contacts app, you can also place Whatsapp and Duo calls to contacts that are not registered.
> 
> Interestingly enough, the Contacts app does know which contacts you can text through Whatsapp and which ones not (not registered).
> 
> It would be also nice to have the option of placing Signal messages through the Contacts app.
> 

Could you open a feature request for this part @NicolasCGN?
