### ISSUE TITLE
Linking device: 'Failed building provisiong image' or 'Registration error'

### ISSUE THREAD

**Issue by dezza** [WhisperSystems/Signal-iOS#2565]
### Bug description
I get `Failed building provisioning image` or `Registration error` everytime I try to register my replaced iPhone via the QR code.

I tried reinstalling the extension/app in Chrome.

### Screenshots
![Screenshot](https://upl.io/i/u1iy6p.PNG)
![Screenshot](https://upl.io/i/dwd1db.PNG)

### Device info

**Device**: iPhone 6S Plus
**iOS version**: 11.0 (15A372)
**Signal version:** 2.16.1.3

### Link to debug log

https://gist.github.com/faa10ccd4dae3236b3e9a0b296b58b89

**Comment by michaelkirk** [comment]
The fix for this will be included in the next release.

If you'd like to try sooner, you can sign up for the beta. By definition, the beta is less tested then the eventual app store release, so there's more likelihood of crashes or data loss, but it would be useful to know if this problem is fixed for you. If you're interested please follow up with support@whispersystems.org with the subject "Sign me up for the Signal-iOS beta re:#256"

**Comment by dezza** [comment]
Good to know. I will keep an eye out.
