### ISSUE TITLE
Spacing triggers a slight OCD

### ISSUE THREAD

**Issue by FiloSottile** [WhisperSystems/Signal-iOS#281]
Sorry if I'm being annoying with these reports, no offense taken if you toss some ^^

I'll speak in CSS terms, since that's basically all I know :)

## Bubble padding

The bubbles have more padding-right than padding-left. Both incoming and sent.

The result is messages feeling off centered, the sent more than the incoming.

## Bubble margin

The sent messages have something like 3x margin-bottom compared to the incoming ones. I'd reduce it, and maybe increase a bit the "Today 03:55" spacing.

**Comment by dtsbourg** [comment]
Hey @corbett 
So regarding this issue : 

# Bubble Padding
tbh I hadn't noticed, and we haven't changed anything from the default behaviour from JSQMessages. If this is something that should be fixed we can take a look there, but imho it's not very problematic.

# Bubble Margin
The padding is voluntary because there was an issue with reloading the cells to make room for the delivered tag : cells would flash on reload, so for the time being we left a constant margin at the bottom. I haven't tried it with the newer performance additions, so feel free to try out some stuff.

**Comment by corbett** [comment]
we will leave detailed padding issues to potential redesign.

**Comment by FredericJacobs** [comment]
@dtsbourg: I strongly disagree on closing stuff just because it's a JSQ imposed decision. Those should be addressed. Maybe not a priority but long term those should be addressed.

**Comment by corbett** [comment]
I agree but it seems like something that should come out of the detailed
re-design visit as a comprehensive list of issues and priorities, not on
offs (as it will get very crowded and some may be duplicates); this doesn't
seem for first launch.

On Wed, Jan 7, 2015 at 10:01 AM, Frederic Jacobs <notifications@github.com>
wrote:

> @dtsbourg <https://github.com/dtsbourg>: I strongly disagree on closing
> stuff just because it's a JSQ imposed decision. Those should be addressed.
> Maybe not a priority but long term those should be addressed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/281#issuecomment-69000981>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by prvcy** [comment]
I know this is closed, but I also wanted to add that there is definitely too much spacing between the sent message bubbles (should reduce it's size once the "Delivered" message disappears).
