### ISSUE TITLE
Can't message contacts initially

### ISSUE THREAD

**Issue by joyceyan** [WhisperSystems/Signal-iOS#383]
When firing up the app initially and opening up any contact, the "call" icon is blue but the "message" icon is grayed out. After ~10 seconds or so the "message" icon becomes blue and I can send messages to my contacts, but there is a delay. This is likely due to the fact that RedPhone and TextSecure contacts are stored separately and the TextSecure contacts have not been loaded in yet.

**Comment by FredericJacobs** [comment]
We have two different contact retrieval techniques:
1) RedPhone Bloomfilter: A bloom filter is fetched from the server. Addressbook contacts are tested against the downloaded bloom filter. Intersection is presented to the user.

2) TextSecure contact intersection API: A list of hashed phone numbers is sent to the server, asking for intersection. Only when that API call is complete, those textsecure contacts are added to the contact list. Hence the little delay since both calls are asynchronous.
