### ISSUE TITLE
Explain how the app finds other Signal users in the address book

### ISSUE THREAD

**Issue by runasand** [WhisperSystems/Signal-iOS#43]
It would be great if Signal (the app and/or the website) could explain what happens with your information when you (a) give Signal access to your address book, and (b) invite friends to use Signal. For example, how does Signal know whether one of your contacts use either RedPhone or Signal?

**Comment by corbett** [comment]
support.whispersystems.org

**Comment by Groxx** [comment]
So since this had some activity and I can't find an equivalent for Android, I'll drop this here for visibility: https://github.com/WhisperSystems/Signal-Android/issues/6750

Since the blog post, support.whispersystems.org, _and_ app don't answer this question, I did some hunting.  I'm not sure if iOS is identical, but it wouldn't surprise me - if so there could / should probably be a cross-app version of that issue.
