### ISSUE TITLE
No confirmation when clicking 'unregister'

### ISSUE THREAD

**Issue by JohanDoe** [WhisperSystems/Signal-iOS#555]
Hi

Even though there is a '>' icon for the 'unregister ' button, the app just closes (or crashes, can't tell the difference) and user is unregistered. 

I suggest to ask for confirmation/inform user for this feature. Or delete the '>' icon. 

Best
Johan

**Comment by corbett** [comment]
this will be fixed in the newest beta coming soon (already fixed in current
code base)


On Sat, Jan 31, 2015 at 12:49 AM, JohanDoe <notifications@github.com> wrote:

> Hi
>
> Even though there is a '>' icon for the 'unregister ' button, the app just
> closes (or crashes, can't tell the difference) and user is unregistered.
>
> I suggest to ask for confirmation/inform user for this feature. Or delete
> the '>' icon.
>
> Best
> Johan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/555>.
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by JohanDoe** [comment]
Just installed 2.0.11 and indeed. 
Tx
