### ISSUE TITLE
Selecting 'Contacts' Crashes the App

### ISSUE THREAD

**Issue by Liongrass** [WhisperSystems/Signal-iOS#615]
Hi! I have the following problem:
After opening Signal I select the *contacts* icon, the app immediately closes without error message.
When taking permissions from the app to access contacts the app doesn't close, but shows the empty contact list instead.
The bug appeared after I underwent a factory-reset of my phone.
I have already tried to deleted my account via the [web interface](https://whispersystems.org/textsecure/unregister/), but the error persists.
Thanks a lot for your work!
Edit: One further detail: When giving Signal the permission to access my contacts, the *Inbox* correctly associates phone numbers with contacts, when it doesnt have permission it lists them as unknown.

**Comment by FredericJacobs** [comment]
Hey @Liongrass,

Thanks for reporting this. I believe this has been addressed already, the issue was related to the way we were handling some special characters.

To make sure it's the same issue as before, can you email me [a crash log](http://bjango.com/help/crashlog/) to fred@whispersystems.org?

Thanks.

**Comment by FredericJacobs** [comment]
I just checked. This issue was addressed in d7bd62ca76ffd266a7d6fde17a6ec59a384dfd27

Should be fixed in next release. Thanks for your report.
