### ISSUE TITLE
Contact listed twice in new message dialog

### ISSUE THREAD

**Issue by Schabernack** [WhisperSystems/Signal-iOS#624]
One contact is listed twice in the signal new message dialog. The contact is actually the merged view of two different datasources (icloud, caldav) for the same person (edit: linked contacts: link contacts), both with the phone number associated with it.  

If the contact is mentioned only once in the apple contact app, i feel signal should align and also show only the merged contact.

**Comment by hubert3** [comment]
+1, also seeing this on a few contacts

**Comment by corbett** [comment]
the user curates their contacts within apple's native contact app
currently. That means if there are two contacts in the native app with the
same phone number, and that phone number is a signal user, the contact will
appear twice. It's intentional currently but something that also frustrates
me as I have many duplicates in the native app.  we'll discuss what to do
about the case further.

On Mon, Mar 2, 2015 at 4:34 PM, hubert3 <notifications@github.com> wrote:

> +1, also seeing this on a few contacts
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/624#issuecomment-76862512>
> .
>



-- 
Dr. Corbett Moran
Physics @ http://www.tapir.caltech.edu <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by bs** [comment]
Seeing this also. Problematic if one uses their phone to manage contacts from multiple sources, which I imagine many users do. (gmail, fb, icloud, ...)

**Comment by michaelkirk** [comment]
Fixed in next release with https://github.com/WhisperSystems/Signal-iOS/commit/06ca3c92909e59c47320a9cc2bb6333222b2368e#diff-8418c8ea3481450157e2ef89c76ed1c1R382
