### ISSUE TITLE
Double messages in groups for user who adds more members

### ISSUE THREAD

**Issue by paintedbicycle** [WhisperSystems/Signal-iOS#628]
Noticing a strage bug where if you create a group with some members, then add more members: you see everyone's messages twice.

If other people look at the "members" listing, you appear in there twice. 

No one else sees the double messages.

If you leave the group and someone adds you back, now you do not see double. However, now they start seeing double messages.

**Comment by corbett** [comment]
this will be fixed by 2.0.1 being uploaded today.

On Mon, Mar 2, 2015 at 1:44 PM, Paul Wright <notifications@github.com>
wrote:

> Noticing a strage bug where if you create a group with some members, then
> add more members: you see everyone's messages twice.
>
> If other people look at the "members" listing, you appear in there twice.
>
> No one else sees the double messages.
>
> If you leave the group and someone adds you back, now you do not see
> double. However, now they start seeing double messages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/628>.
>



-- 
Dr. Corbett Moran
Physics @ http://www.tapir.caltech.edu <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by paintedbicycle** [comment]
@corbett Thanks!
