### ISSUE TITLE
Signal doesn't show all contacts

### ISSUE THREAD

**Issue by RanaExMachina** [WhisperSystems/Signal-iOS#644]
I have updated Signal yesterday to the new version which supports encrypted text messages. It tried to find my contacts but now it lists only two contacts. I know that more of my contacts are using Signal/ChatSecure. They can write me messages and when I try to answer them I'm told that they are not registered. After that I can write them messages but they don't show up in my contact list.

**Comment by FredericJacobs** [comment]
Hey @RanaExMachina,

You should see all your contacts by tapping on the "+' on the main screen and then scroll to refresh on that contact view. That should work.

Let me know

PS: We're TextSecure on Android, not ChatSecure

**Comment by RanaExMachina** [comment]
I already tried that. Signal lists only the two contacts.

**Comment by manishvij** [comment]
+1 A friend of mine with my phone number in his contacts installed Signal yesterday, verified his phone #, and has same problem, didn't see me in his contacts.

**Comment by RanaExMachina** [comment]
Okay, I now know what the problem is. I had most of my contacts' numbers beginning with a 0 instead of the countrycode. This works fine for normal phone calls, SMS, WhatsApp and iMessage but not for Signal. After I replaced the 0s with the correct countrycode (+49 in my case) they showed up in my Signal contact list.

**Comment by FredericJacobs** [comment]
I have an enhancement for this in 2.0.1. Let me know when it comes out if it detects more numbers.

**Comment by FredericJacobs** [comment]
@RanaExMachina : Did 2.0.1 improve contact discovery for you?

**Comment by RanaExMachina** [comment]
Yes, all three variants (0, +49, 0049) for my country code seem to work. :)

**Comment by mike1137** [comment]
Hi Frederic

I am having the same issue. I am running Signal Version 2.2 and Iphone OS 9.3. Please advise, Thanks,

**Comment by CumpsD** [comment]
Same here on iOS 9.3.1 and signal 2.2

Only a limited amount of contacts show up, even though all number formats are equal

**Comment by michaelkirk** [comment]
@mike1137, @CumpsD - Are these contacts Signal users?

Make sure you've read:
http://support.whispersystems.org/hc/en-us/articles/212476148-Who-can-I-talk-to-with-Signal-Where-are-my-contacts-
http://support.whispersystems.org/hc/en-us/articles/213133077-What-settings-or-permissions-do-I-need-to-enable-on-my-iPhone-

**Comment by CumpsD** [comment]
Right, sorry, that was the case. They show up now.

**Comment by wangxcharlie** [comment]
Signal ver. 2.11.3, after updated iOS to 10.3.1, only a few contacts showed up. My friend can send me message, but when I reply, it says message not delivered and shows the recipient is unregistered. Tried everything listed above, still doesn't work.

**Comment by littlesandra88** [comment]
On my iOS 9.3.5 I can only see the Signal users in the list. If I click Invite then I can see the entire contact list. But never for writing normal messages.

**Comment by darrenchaker** [comment]
I had similar issues with Signal toggling between Google contacts and contacts saved to the phone. I now simply save all contacts to the phone and deleted Google contacts for privacy reasons. It now works fine. 
Best to all! Darren Chaker [www.blogdarrenchaker.com](url)

**Comment by moore-bryan** [comment]
Is there an actual resolution to this other than making sure all contacts are saved to the phone?

**Comment by blahdeblahde** [comment]
I'm still having this issue and have had problems across multiple versions of Signal and iOS. Currently on Signal 2.26.0.26 and IOS 11.4 and since reinstalling the current version I have no contacts at all and when I try to add a number to an existing contact it only shows me myself.

**Comment by michaelkirk-signal** [comment]
@blahdeblahde - can you verify that you have given Signal contacts access in System settings > Privacy > Contacts

And can you verify that any of those people are Signal users? We only show those of your contacts who are also Signal users.

**Comment by sybercorp** [comment]
This is still an issue in 4.34.8.  Seemingly random contacts don't show up in the search list. You can type in their number manually, and it does match their number to their contact name, to display in the conversation list. Even after that, if you search for them again, they still don't show up in the search list. Pulling down on the contacts list to refresh it makes no difference. Toggling permissions on contacts makes no difference.  No, not just Signal contacts are listed.  Some of the people NOT listed are NOT Signal contacts.

**Comment by 8986ca6c** [comment]
Hi sybercorp, you are using the Android App (know that from your version number). Did you try what the developers suggest on their support site? See https://support.signal.org/hc/en-us/articles/360007319011-Edit-or-Update-Contacts for more details. 

Besides that there is a solution (by hacking in the Android-Accounts-Settings-stuff), there should be a more convenient way. Also the iPhone-App requires a action of the user. Hope this will improve in the future. So that I can fully rely on that the App is showing all my contacts, that are using Signal.

**Comment by carljm** [comment]
Just another note to echo @darrenchaker -- for me this problem was because I had an Exchange account (as well as iCloud and Google) set up as a source of contacts in my iPhone, and the Exchange account was set as the default save for new contacts (and I didn't realize that). So Signal couldn't see any of the new contacts I was unintentionally saving to Exchange. Changing the default contact save to iCloud in my iOS settings (and then using the Outlook iOS app as outlined at https://discussions.apple.com/thread/8393666?answerId=8393666021#8393666021 to re-save all my Exchange contacts to iCloud) caused them to become visible to Signal.
