### ISSUE TITLE
Error inviting a contact without giving Signal access to your address book

### ISSUE THREAD

**Issue by TheStash** [WhisperSystems/Signal-iOS#665]
Issue description:

1. I've blocked Signal from accessing my address book.
2. Went to initiate new conversation
3. Got the "Sit tight"... i sat tight
4. Signal: "None of your contacts have Signal! Why don't you invite someone"
5. i click "Invite contact"... thinking i will invite him via telephone number
6. App goes to "conversation view" and nothing happens.

I believe that after 2, the app should ask me for access to contacts like:

![img_3152](https://cloud.githubusercontent.com/assets/11326414/6500658/df124ebc-c30e-11e4-8c3f-3392aaf97ff2.png)

and if i didn't give it access and hit "invite contact"... Signal prompts me to enter their number, or request to have limited access to contacts (i think this would be helpful: https://lmjabreu.com/post/ios-8-privacy-updates/#contacts ), for example access to a specific contact, access to phone addresses of contacts only (without access to their full information)... i'm not sure if you can pic a specific contact and select that you want to give the app access to only his phone number but not his email address or not.

Thank you for your work @FredericJacobs @corbett @abolishme :-)

**Comment by FredericJacobs** [comment]
Thanks, this should indeed be done.

**Comment by Lolina18** [comment]
I had the same problem. The suggested solution would be very helpful, especially since I don't want to give access to all my contacts.

**Comment by Lolina18** [comment]
Actually, today I finally found someone willing to try the Signal with me. That person installed Textsecure and Redphone, and granted access to his contact list. He sent me a message via Textsecure and I got an encrypted SMS instead of a message in Signal. He then removed access from his contact list and send me an invitation SMS. Next he called me through Redphone and I finally got a call on Signal - but couldn't pick it up. I could call back but now he could not pick up. I still could not send messages via Signal to him, so I had to give it up. Without granted access to the phone book nothing works. :(

**Comment by MrAndMrsK** [comment]
Absolutely!  I would never give access to my contact list from an app, but I would be willing to put in one phone number at a time, and provide a nickname for that contact in a Signal-only contact list.  

Now perhaps this is just a "truly, just no one has gotten to it yet" situation and if so please disregard this next bit, but the *appearance* is that this is an intentional limitation to extract valuable social network information and correlated names, phone numbers, email addresses, etc for Twitter or whoever, and that seems to me an ironic goal, given that this is an app attractive to security-minded folks.

**Comment by WeeBit28** [comment]
Inviting contacts without having to give permissions to your address book would be great. It's the only thing keeping me from using the app so far.

Great project and initiative btw. I truly hope that people give it the attention it deserves.

**Comment by FredericJacobs** [comment]
Fixed in https://github.com/WhisperSystems/Signal-iOS/commit/c95f190140ba00048983d07289082e497d702947

**Comment by thomaslissajoux** [comment]
Sorry I don't see how this is fixed in any way
I still cannot use signal without granting access to my contact list !!!
