### ISSUE TITLE
Attachment icon is not clean

### ISSUE THREAD

**Issue by vodnar** [WhisperSystems/Signal-iOS#716]
It looks somehow jagged, at least on iPhone 5s.
![signal-attach-icon](https://cloud.githubusercontent.com/assets/1723015/6651956/014c748a-ca5d-11e4-8f7b-a669a49ee4bf.png)

**Comment by FredericJacobs** [comment]
This is likely an Xcode issue since we're using [vectorial assets](https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/Images.xcassets/btnAttachments--blue.imageset/btnAttachments--blue.pdf) that should be exported at the right resolution. Hopefully this will resolve itself with the next version of Xcode.

**Comment by michaelkirk** [comment]
The sub-pixel guessing that must be done when resizing images to their native resolutions can causing pixel artifacts like this. One way to fix this would be to manually exporting the final 1x,2x,3x resolutions from the vector and touching up each asset to make sure it's crisp.

**Comment by jooize** [comment]
As Xcode hasn't fixed the issue in over a year, such an approach would be appreciated in the meantime.

**Comment by michaelkirk** [comment]
fixed in https://github.com/WhisperSystems/Signal-iOS/commit/6bd2453d7d91c0028616076b18823b1577f4b817
