### ISSUE TITLE
Crash after restoring phone from backup

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#746]
Apparently some place holder files are put in the Documents directory after restoring from iCloud backup resulting in a crash on the next launch when trying to re-register.

Temporary solution is to re-install the app manually.

Longer-term solution is being worked on.

**Comment by CodingAnarchy** [comment]
I can confirm this also occurs when upgrading to a new iPhone. Glad to see its already being worked on.

**Comment by FredericJacobs** [comment]
I have a fix that should be in the next release.

**Comment by FredericJacobs** [comment]
Fix merged in master!

**Comment by rmueller83** [comment]
A friend of mine made a backup on an iPhone 5s and restored in on a 4s. Since then, Signal crashes on startup. This was the case in the previous version as well as in the current 2.1. He can see the Signal logo and shortly the update notification, then the app closes. Is there a way to delete the app data from the phone?

**Comment by FredericJacobs** [comment]
@rmueller83: Reinstall the app is only way

**Comment by rmueller83** [comment]
Okay, that worked. Thank you!
