### ISSUE TITLE
No Push Notifications on iOS 8

### ISSUE THREAD

**Issue by davidbilge** [WhisperSystems/Signal-iOS#761]
I recently installed Signal v 2.0.2 on my iPhone (5s) and do not receive Push Notifications on incoming messages.

In iOS' settings-app, under Notifications, Signal does not appear. Thus, I have no way of configuring the notification settings.

**Comment by zbroyar** [comment]
Have exactly the same problem on 2 5s devices.

**Comment by FredericJacobs** [comment]
Currently looking into it.

**Comment by Theoderich** [comment]
Same here on iPad Mini 2

**Comment by peterpanondrugs** [comment]
Same here.
Reinstalled and removed phone number from signal multiple times. Still the same:

For the security category "Mitteilungen (Messages/Notifications?)" there is the app "Signal" not shown.

**Comment by FredericJacobs** [comment]
I have a fix pending with Apple.

So sorry about this. Your phones are receiving the notification but not displaying it.

**Comment by 2-4601** [comment]
Cannot reproduce on iPhone 4s with iOS 8.2.

Tested with messages:
- phone locked: works
- phone open on home screen: works
- Signal open: works

Rebooted phone and tested all of the above again. No issues.

Signal is listed in the System settings notifications.

(Forgot to test with calls. Cannot redo test - not my phone.)

**Comment by zbroyar** [comment]
AFAIU, it�s not reproducible on any device except 5s.

**Comment by 2-4601** [comment]
@FredericJacobs Did you request an expedited review for this fix or does it go through the regular process?

**Comment by FredericJacobs** [comment]
Expedite review

**Comment by davidbilge** [comment]
Frederic, thank you for looking into this so quickly. I'm impressed! 👍

**Comment by 2-4601** [comment]
@FredericJacobs Thanks!

Could you elaborate what caused the bug and which devices and iOS versions are affected? Helps to know which friends are supposed to receive push for my messages and which not. (Asking through other messaging apps would just make Signal look bad :)

**Comment by FredericJacobs** [comment]
Start monitoring the App Store. A fix has been released (approved under expedite review). No re-install necessary. Next time you open the app after the update you will be prompted about push notifications.

I'm unsure about the range of devices/firmwares that were affected. I was definitely able to reproduce it on an iPhone 5. I believe most of them were actually incorrectly registering for notifications. Bug was caused by legacy code. Push notifications and local notifications used to be the same API call. Now they are separate and only one call was successfully made.

Local notifications are now always verified on launch of the app. Will make supporting UIUserNotificationCategories easier to support and maintain.

**Comment by davidbilge** [comment]
Update installed, works like a charm. Great!

**Comment by nodomain** [comment]
I have still the issue on iOS 9.1 with an iPhone 5s. I can not receive notifications and neither register for Signal. Furthermore I can not find the app under notification settings. Please advise.
