### ISSUE TITLE
Conversation with new messages remains in archive

### ISSUE THREAD

**Issue by maltemayer** [WhisperSystems/Signal-iOS#813]
Someone send me two messages, but the conversation remains in the archive view.

![signal-message](https://cloud.githubusercontent.com/assets/5073538/8039992/6da7ce92-0e0d-11e5-8f3b-1736472ffc2d.png)

**Comment by FredericJacobs** [comment]
Do you have more information about what those message were?

**Comment by michaelkirk** [comment]
As I understand this report:

Alice sends Bob a message.
Bob archives thread.
Bob moves to the archive tab.
And sees his thread with Alice.
Alice sends Bob another message.
Bob sees a (1) in the inbox tab, but Alice's thread still appears in the archive tab.

I cannot reproduce the above, so assuming it's since been resolved. If it's a different issue please provide steps to reproduce.
