### ISSUE TITLE
Support ZRTP key continuity

### ISSUE THREAD

**Issue by Geblaat** [WhisperSystems/Signal-iOS#822]
For an app that wants to be user friendly, having to authenticate the SAS only once would be a great improvement. The "self-healing" properties againts MitM are a nice plus as well.

**Comment by Calefornia** [comment]
Are you referring to the short authentication string that shows up during a phone call? Unless I'm mistaken, that's necessary to be sure you aren't being attacked, because an attack could occur at any point in the future. For a long time, Signal has benefited from the forward secrecy and "self-healing" properties. See this [blog post](https://www.whispersystems.org/blog/advanced-ratcheting/) from November, 2013.
Perhaps the issue of being user friendly is more about UI/X than underlying security features.... I haven't used Signal for a while, but I'm back on it and playing around with the app.

**Comment by Geblaat** [comment]
@Calefornia
The blog post you linked to is about the messaging protocol, it does not apply to phone calls. For phone calls Signal uses the ZRTP protocol.
See: http://zfoneproject.com/faq.html#keycontinuity
And: https://blog.cryptographyengineering.com/2013/03/09/here-come-encryption-apps/ ("Other thoughts" section under Redphone/Textsecure

**Comment by Calefornia** [comment]
My apologies.... I am not very familiar with this and shouldn't have commented. Thanks for the insightful links! Sorry to distract everyone with unnecessary comments 😬

**Comment by TreatyOfRome** [comment]
Could be closed due to implementation of WebRTC calling?

**Comment by michaelkirk** [comment]
We no longer use zrtp. see https://whispersystems.org/blog/signal-video-calls/
