### ISSUE TITLE
VersionMigrationsTests destroys keying information

### ISSUE THREAD

**Issue by Strilanc** [WhisperSystems/Signal-iOS#829]
When VersionMigrationsTests runs, it mutates global state used by the app. It replaces your local number, your password counter, mac key, cipher key, etc with dummy values.

This causes the app to fail to make calls the next time you start it, because it fails to authenticate (due to no longer having its keys).

Also, the dummy value for the saved password is not encoded as base64, so *really* the app will simply crash on startup when it tries to read it.

(These kinds of tests make the dev experience very poor. The functionality should be tested without affecting the actual app state.)

**Comment by FredericJacobs** [comment]
@Strilanc : I'm not sure I know what you're referring to. A lot of the things have been refactored since we moved to a single storage. We needed more than storing to local .plist files for the messaging component of the app. So when the app migrates from v1 to v2, it does copy the keying material to the new storage and deletes it from where it was previously. We have had no issues with this transition in production.

**Comment by FredericJacobs** [comment]
Agreed that we could be doing better at this. But as of right now I'm always splitting my testing environment with my production one.

**Comment by FredericJacobs** [comment]
This is no longer an issue
