### ISSUE TITLE
SignalUtil.m signalingCipherKey Sent Twice

### ISSUE THREAD

**Issue by a432511** [WhisperSystems/Signal-iOS#843]
Good morning,

Any concern over sending signalingCipherKey twice in the same body? Doesn't that weaken against cryptanalysis attacks?

Cheers,

Adam

SignalUtil.m - lines 99-101
  
    NSData* signalingCipherKey = SignalKeyingStorage.signalingCipherKey;
    NSData* signalingMacKey = SignalKeyingStorage.signalingMacKey;
    NSData* signalingExtraKeyData = SignalKeyingStorage.signalingCipherKey;

**Comment by Strilanc** [comment]
Good catch! Looks like a typo happened during [this commit](https://github.com/WhisperSystems/Signal-iOS/commit/6dd04a49fe811822ed88e3eb1fe68ddde6e4e563).

I think it's not deadly serious, because the data is being immediately hashed. Some entropy is being lost, but the stuff already being hashed has lots of entropy.

I'm surprised this works, actually. I would expect the challenge response to be wrong and fail...? Might be tricky to fix without causing compatibility issues.

**Comment by FredericJacobs** [comment]
@Strilanc : Can you point to me where in that commit the typo happened? I don't see that.

This is not an issue because we're not using the extra key data material. Additionally, TLS is not ECB-mode encrypted so repetitions should not be an issue cryptanalysis-wise ;)

**Comment by Strilanc** [comment]
Huh, I must have misread the diff. You're correct that the error is not in that commit. My mistake.

**Comment by FredericJacobs** [comment]
This has been corrected for new users. Since there is no security risk involved for previous users, we are not registering a different extra data key (that are currently unused and probably won't be used in the future, code has been commented to indicate that).

Thanks for spotting this @a432511.
