### ISSUE TITLE
Possibility to download media files only if Wifi is available

### ISSUE THREAD

**Issue by Zahlentheorie** [WhisperSystems/Signal-iOS#856]
Or by pressing the preview of the picture or video.

**Comment by FredericJacobs** [comment]
We can't show a preview of the picture or video. 

Other messengers achieve this behavior by generating a smaller preview on the server. Since our server is unable to decrypt attachments or messages, it is not an option for us.

We are also not interested in having a "WiFi only" option for downloads of attachments. Image sizes right now are reasonable. If we end up having higher sizes images or attachments being sent on the app, we will reconsider this setting.

**Comment by Zahlentheorie** [comment]
I would welcome this feature because it's more comfortable to send pictures and videos on Signal than in email because most of my friends aren't using PGP. It probably sounds weird but I would feel more secure to use Signal in those cases.
