### ISSUE TITLE
UI in latest version (2.1.2) for iPhone completely unusable for calls

### ISSUE THREAD

**Issue by occbaystreet** [WhisperSystems/Signal-iOS#863]
It's also virtually useless for texts. I used previous versions (pre-texting capability update) for over a year with my iPhone 4 with mostly very good results. The Contact I spoke with most will not show up now no matter what I do. I also, as reported by others, get no phone icon with any of my Contacts. I have turned phone on and off. I know several of my contacts with Signal to be iPhone users for 100% sure.

**Comment by moxie0** [comment]
Useless? This report seems pretty useless to me.  If you would like to be helpful, what's needed is a specific description of a single problem you're experiencing, steps to reproduce, and a debug log.

If, as you suggest, there is already an issue open for your specific problem, then please add any new information there rather than opening a duplicate.
