### ISSUE TITLE
Signal eats too much traffic

### ISSUE THREAD

**Issue by JimLoose** [WhisperSystems/Signal-iOS#866]
I don't use signal that much, especially not that much for multimedia.
Anyway Settings > Mobile > shows me 155MB for what?

What needs that much traffic in Signal? (much more than Whatsapp (8MB))

![img_0924](https://cloud.githubusercontent.com/assets/195000/9192894/6afdda68-400f-11e5-8373-68c75277cec5.PNG)

How much is your data usage? It would be great if you could please look into that issue.

**Comment by hubert3** [comment]
Probably this feature: https://whispersystems.org/blog/contact-discovery/

Which means you can discover contacts on Signal without uploading your entire address book, as Whatsapp and most other apps do.

**Comment by TuxDev1337** [comment]
So how to disable that? I don't want that anyway.

**Comment by TuxDev1337** [comment]
I would appreciate if somebody could investigate this. For me Signal is unusable if I am not at home, since I don't want to spent all of my data volume for something that is not really useful for me. There should be an opt-out for that contact checking.

**Comment by FredericJacobs** [comment]
We are working on this. Will post an update soon.

**Comment by TuxDev1337** [comment]
Awesome :D Thank you!

**Comment by evanchaney** [comment]
I have also experienced this issue. I am seeing Signal consume cellular data at a rate of about 5–10MB per day without launching the app or allowing it to use background refresh.

**Comment by evanchaney** [comment]
Lending some credence to hubert3’s guess, I have updated 3 contacts in the iOS contacts app over the last week which looks like it triggers a refresh of Signal’s contacts (presumably in the background):

https://github.com/WhisperSystems/Signal-iOS/commit/e8ea00d71a4b72a4b7a2e9bfaf2026dafbe1b064

**Comment by JimLoose** [comment]
> We are working on this. Will post an update soon.
??

This is still a very big issue without any clear explanation or fix!
My contract only has 500MB and Signal eats most of it, that's why i and most of my friends removed it for the now!

**Comment by dan-tum** [comment]
Same here, in the last 3 months I have 450 MB of Signal cellular usage while only using it with one single friend and I only use texting. It has used more data than Safari, Facebook and Alien Blue, apps which I use very often.

**Comment by alasyon** [comment]
I'm having the same issue. Uses 70-100MB per day, sending 10-20 text-only messages. My data cap is 2GB/month, so if I use Signal then it single-handedly uses the entire cap. Makes it unusable for myself and most of my iPhone owning friends.

**Comment by FredericJacobs** [comment]
Removed on master.

**Comment by JimLoose** [comment]
what's the new solution?

https://github.com/WhisperSystems/Signal-iOS/commit/26f9207cab06e4df4af3dc9c02deca3d250eb4ae

**Comment by Chabulga** [comment]
is this version already uploaded to apple?

**Comment by FredericJacobs** [comment]
No. Apple is closed for the Holidays.

**Comment by Nichtoderman** [comment]
I experience the same monthly volume usage behavior. Is there any progress in this case?

**Comment by peterpanondrugs** [comment]
I know u stopped working on Signal, but can u push this...
My people are refusing/deinstalling the iOS version: espc. because of high traffic
Wish you best for the future. Thanx for all your work.

**Comment by hadinbe** [comment]
Why is this issue closed? It's not solved as far as I can see...

**Comment by jamezpolley** [comment]
This still seems to be an active issue. I have just had Signal chew through 600Mb of data in the last week even though I've only opened it twice and received two messages.

Is therere any word on when the new verersion will be released?

**Comment by Chabulga** [comment]
If it true what is written above, the bug is fixed in 2.3 but no one tells us when it is released even via Twitter no one answers. This was a very major issue in my opinion and should deserved a very fast fix. But the moment to fix this is long gone. My folks sadly all left Signal because of the traffic. Fixing it now would not change anything anymore. Too bad...

**Comment by hadinbe** [comment]
The release 2.3 has still 10 open issues out of 22, so except if these are pushed to 2.4, we won't be seeing 2.3 in a while. Source: https://github.com/WhisperSystems/Signal-iOS/milestones/2.3

**Comment by Ewarren7** [comment]
For what it is worth, I noticed on a firewall traffic log that Signal pulled down ~ 7 MB in 2 hours and I had not touched the app in days. 

![image](https://cloud.githubusercontent.com/assets/7004081/13395132/c6f9799a-deba-11e5-8d00-9d2c9fa18802.png)

**Comment by scimax** [comment]
I'm actually using the Android client but my contacts leave Signal on iOS at the moment due to this issue. 300 Mb within a week although no media data was sent.

**Comment by peterpanondrugs** [comment]
@moxie0 can you organize a PR for that bug? 
As i wrote Frederic in email: "whats the app worth if ppl are not using it due high traffic...all that effort! "
I will organize crowdfund money if u need ... 
Thanx in advance.

**Comment by michaelkirk** [comment]
@peterpanondrugs - as said earlier in the thread, the code resolving this issue is in master. Pending an app-store release this will be available to all Signal iOS users.

**Comment by ghreat** [comment]
It is still an issue. I don't use signal that much, but I have a few people on my list. Just checked cellular use for it today and saw a whopping 2.4 GB. That is insane. Way more than Safari and Chrome use put together for the same period and they are used way more frequently on the run and with much more rich media.

**Comment by pc1oad1etter** [comment]
@michaelkirk Can you update here when this is available in the App Store?  I'm seeing 20% of my data usage coming from Signal, which I only use a few times a month for texting.  I do not have unlimited bandwidth and it makes me want to abandon what I otherwise consider to be such a great app, and which I convinced other friends to adopt.

**Comment by michaelkirk** [comment]
@pc1oad1etter it's fixed in the current beta. 

You can speed up the release by signing up and providing feedback:
https://whispersystems.discoursehosting.net/t/call-for-ios-beta-testers-email-support-to-sign-up/349

**Comment by pc1oad1etter** [comment]
Excellent, thank you.

**Comment by ghreat** [comment]
Just an update, in the 24 days since my last post it has used on average 50 MB of data per day over cellular. That is 1.2 GB in less than a month for a texting app (that I barely use). Most of my days I am on Wi-Fi, whatever it uses during those hours are extra on top of those 1.2 GB.

Is it hard to backport the bugfix to the current version of Signal for iOS and push that update if the "next" version is not ready for the real world yet? I've heard that app review times for the AppStore is now less than 24 hours and you've had a fix (26f9207) for it since November 29th, 2015 according to a previous post in this thread. 

Isn't this bug severe enough to push the fix for it within half a year? BTW, there's still time to do it! 😄

**Comment by monomeric** [comment]
Will the fix be pushed soon? Receiving a short, 20 character text earlier today used up about 300 kB! I had to turn off cellular data use for Signal, which makes it currently pretty useless for me. iPhone 4S, iOS 9.3.2, Signal 2.3.2.

**Comment by michaelkirk** [comment]
@monomeric this issue is related to a viscous cycle of re-downloading contact discovery data even while the app is idle. That should be addressed in all version of signal post 2.3 (including yours).

It sounds like you're describing something else related to *sending* messages. If you are seeing hundreds of kb per plain text sent, that's a bug. Could you open a new issue explaining exactly the steps taken, how many messages and the data spent?

**Comment by pc1oad1etter** [comment]
Thank you very much for fixing this bug!  I'm happy to see my Signal traffic at less than half of a megabyte, much more what I'd expect for only sending a couple of texts!  Good work.

**Comment by Amalinda** [comment]
hi, I did a comparison of video calls with Signal and WhatsApp for data usage. It seems Signal is much more hungry for data. Am I mistaken or is this the same experience by everyone else?

**Comment by michaelkirk-signal** [comment]
Hey @varenc - The root cause of this issue, as it was filed, is definitely fixed. None of that code exists anymore.

But Signal is fundamentally a network app, so it's possible that two years later a new and different cause of unnecessary traffic has arisen.

Can you please open a new issue and include a debug log?

Do you have a way to monitor your outgoing network traffic on your phone? It would be *especially* helpful if you could put some time into figuring out what scenarios correspond to surprisingly large amounts of network activity. 

One thing I'm curious about is if you unlink your linked desktop if the network usage seems more reasonable.
