### ISSUE TITLE
Save messages for import when moving phones

### ISSUE THREAD

**Issue by jni** [WhisperSystems/Signal-iOS#905]
I just upgraded to iPhone 6s, and all my Signal messages are gone, despite restoring from backup. Is this expected behavior?

Thank you!

**Comment by FredericJacobs** [comment]
It is expected behavior. We currently do not have an import/export feature.

iTunes backups are disabled to prevent plaintext leakage to iCloud or insecure systems.

**Comment by jni** [comment]
Couldn't you do as Apple does with health data and allow backups when they are encrypted? (Maybe letting the user decide if they are ok with this?)

**Comment by FredericJacobs** [comment]
Gonna see how that works.

**Comment by NiklasBr** [comment]
I'm curious to know if there is any progress on this issue. Can I pledge something? I too lost my messages when I got a new phone and would very much like to restore them.

**Comment by NiklasBr** [comment]
I understand that this feature is available on Android but not on iOS. Can't you do what jni suggests and only backup to encrypted backups?

**Comment by vsivsi** [comment]
Whisper Systems unceremoniously locked the open issue thread on this at #2542.

To be crystal clear: this issue is a critical flaw leading to the eventual **certain and total loss** of *each and every* user's data: their complete message history and all verified contacts; when they inevitably lose, destroy or replace their device.  

No phone is forever, and so neither is anything you have stored in Signal.

Given this, Signal should be considered unsafe for anything but truly ephemeral communications with people you have regular personal (secure, outside of Signal) contact with.  

WS appears to be giving no priority to fixing this critical flaw (as I write this issue is 28 months old.)

If you are a Signal user and care about your data, may I suggest you make yourself heard (and warn others) via a constructive review on the iOS App Store, and on this thread in the WS discussion forum:

https://whispersystems.discoursehosting.net/t/encrypted-backup/1227

**Comment by gojomo** [comment]
I protect my encrypted iPhone backups very well - perhaps as well as Signal protects the encrypted phone numbers they want to repeatedly upload to Signal matchmaking servers! So I should really have the option of porting my histories to a new phone via that method. Other security conscious apps, like Google Authenticator, transfer smoothly to a new phone via this method.

**Comment by sparr** [comment]
Not only does this make Signal unsafe, but by training users to automatically accept re-verification requests from contacts who have new keys they are destroying people's already-weak understanding of good security practices.
