### ISSUE TITLE
Signal-iOS fails to send when it thinks there are more devices for an account than actually exist

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/Signal-iOS#907]
https://gist.github.com/mcginty/890d15e1f2da4cd62c04
(logs collected from someone else's phone and I scrubbed my number)

At one point I had 3 devices attached to my account, and I no longer do. Friend was able to send me messages successfully at one point in time, can still receive all messages I send, but was no longer able to send, presumably due to this 404 when trying to receive prekeys for a device that no longer exists in my account.

Just to check, I brought my device count back up to 3 by re-registering the browser extension twice and he can now send me messages.

**Comment by liliakai** [comment]
In the log above, the client had record of the recipient's deviceNumber 3, but had no open session with that device. When the client tried to fetch a prekey for device 3, (which had been recently unregistered) the server returned a 404 to [the prekey request](https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/textsecure/Messages/TSMessagesManager%2BsendMessages.m#L230) in the function `encryptedMessageWithPlaintext`, which throws an exception, and causes its caller to [return early](https://github.com/WhisperSystems/Signal-iOS/blob/master/Signal/src/textsecure/Messages/TSMessagesManager%2BsendMessages.m#L217)  before sending any messages.

EXPECTED BEHAVIOR: upon receiving a 404 to a prekey request for a particular device, the program removes that device from the recipient's device list, and proceeds to encrypt and send to the remaining known devices.

**Comment by liliakai** [comment]
I don't have any idea what I'm doing when it comes to iOS/Objective C, and also I don't have an iOS dev environment set up, but I'll leave this here in the hopes that someone (who does have both those things) can take it and run with it:

https://github.com/liliakai/Signal-iOS/commit/cd3ce9550ecb760fabc3cd7abc719ab207baf762

**Comment by FredericJacobs** [comment]
Thanks Lilia, I'll try this on Monday since I don't have any test device with me.
