### ISSUE TITLE
Address "double-sends"

### ISSUE THREAD

**Issue by FredericJacobs** [WhisperSystems/Signal-iOS#951]
**Problem:** A common issue in single chats & group chats is to receive messages twice. The likely cause of most of them are issues on the message sending HTTP API that results in synchronous calls that can take some time to return. By that time, the call might time out or be interrupted by network signal dropping.

**Solution:** This will be mitigated on the client-side by generating and storing the ciphertext of a given message along with the failed message in the local database.

This will prevent the message from being unnecessarily re-encrypted on when reattempting to send it. And if received twice, the receiving client will not process it a second time since keying material will already be gone. Yah, perfect forward secrecy!

Some checks might need to be added to handle changes in `registrationId` or `deviceId`s.

Ideally, sending messages should become an asynchronous task for the server over the WebSocket.

**Comment by michaelkirk** [comment]
> Solution: This will be mitigated on the **client-side** by generating and storing the ciphertext of a given message along with the failed message in the local database.

By client-side you mean **sender** side, right?

The *sender* will store the cipher text of the message locally. Then, when retrying the send, she will send the previously generated ciphertext rather than re-generating new cipher text.

Just diving through the message sending/receiving code now... :+1:

**Comment by michaelkirk** [comment]
Far and away the most common cause of this that I've seen is due to accepting new identity keys. 

When attempting to send to a recipient whose identity key has changed, the message fails to deliver to that user, but succeeds in delivering to all other users.

When you tap on the "identity key changed" warning message, and accept the new identity key, Signal resends the message to the *entire group*. Instead, we should resend *only* to the user with the newly accepted key.

**Comment by 2-4601** [comment]
I think double sends might some times happen when the iOS user writes a message, taps send and immediately goes to iOS home screen. Then when they return back to Signal, the message gets sent again.
This is just an observation from a non-iOS user and completely anecdotal.
