### ISSUE TITLE
Received notification to accept new identity key

### ISSUE THREAD

**Issue by katiekatia** [WhisperSystems/Signal-iOS#953]
Hi

I'm new to encryption and just received a notification when trying to send an encrypted message via Signal saying I needed to accept a new identity key for the person I was trying to contact. We had previously been sending encrypted messages using the same app, so I don't now why this would come up now - is this normal and should I accept the new key?

Thanks
Katie

**Comment by FredericJacobs** [comment]
Hi @katiekatia,

Yes this is normal. It means the other recipient changed encryption key. You might want to check with them whether they changed phone or re-installed the app.

I agree that we can do a better job at making the warning clearer to users because the current situation can be very confusing for users who never used encryption software before. We'll work on that.

Best,

Frederic
