### ISSUE TITLE
App not respecting active DoNotDisturb #2

### ISSUE THREAD

**Issue by dibblah** [WhisperSystems/Signal-iOS#983]
"Apple doesn't give us the APIs for it." - Frederic Jacobs

How come Skype & Facebook Messenger notifications are muted by DoNotDisturb then? And all other app notifications too ...

Do you mean that Apple gives them the APIs but not you?

**Comment by FredericJacobs** [comment]
I believe we're only doing this for phone calls, not messages. Right?

**Comment by dibblah** [comment]
Asked a friend to send a message, like you said no notification.

But call notifications gets through DND

But notifications for calls should be possible to stop right?  since Skype calls are muted?

I actually thought that you couldn´t get a notification through even if you wanted to, was really surprised the first time it happend. I thought DND mute was handled by iOS.

**Comment by FredericJacobs** [comment]
There is a trade-off to make: either we respect do not disturb for calls, but that means that we can't get continous vibration when the phone rings or we stick with the current situation.

I would lean towards sticking to what we have now because not getting continuous vibration when the phone rings is actually way worse IMO. Eventually I think we could have a setting for explaining this trade-off. But standard behaviour would still be what we have now.

**Comment by dibblah** [comment]
IMO the app disturbing me when I don´t want it to ring .. ie sleeping meeting etc .. is much worse than it not vibrating continously. A setting would be very nice so I can turn off this annoying "feature"

**Comment by voltagex** [comment]
Breaking the user's expectation of what Do Not Disturb means is pretty bad

**Comment by pjctech** [comment]
Use CallKit for voip calls.
https://developer.apple.com/reference/callkit

It gives the Call Blocking & Identification and Do Not Disturb for free.

**Comment by TreatyOfRome** [comment]
With the implementation of WebRTC calling (and CallKit integration), this issue should be fixed. I can't reproduce this issue anymore. When turning on DND, my incoming calls (and messages) are muted.
